### ISSUE TITLE
Upgraded to 3.4 - Cannot set property 'marked' of undefined

### ISSUE THREAD

**Issue by trueter** [exceljs/exceljs#1027]
Downgrading to 3.3.1 avoids the problem. 
Difficult for me to say what exactly causes the problem as the error is raised only when writing the sheet to file.
```
(node:57552) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'marked' of undefined
    at .../node_modules/exceljs/lib/xlsx/xform/sheet/data-validations-xform.js:77:40
    at Array.map (<anonymous>)
    at .../node_modules/exceljs/lib/xlsx/xform/sheet/data-validations-xform.js:54:6)
    at .../node_modules/exceljs/lib/xlsx/xform/sheet/data-validations-xform.js:105:28)
    at .../node_modules/exceljs/lib/xlsx/xform/sheet/worksheet-xform.js:233:30)
    at .../node_modules/exceljs/lib/xlsx/xlsx.js:532:22
    at Array.forEach (<anonymous>)
    at .../node_modules/exceljs/lib/xlsx/xlsx.js:530:22)
    at .../node_modules/exceljs/lib/xlsx/xlsx.js:623:16)

```

**Comment by dadlian** [comment]
Thanks man this saved me from a nightmare meeting with a client!

**Comment by cooperbrown9** [comment]
How did you solve it?

**Comment by andersevenrud** [comment]
I had to downgrade to 3.3.1 in order for this to work again. The latest 3.7 has the same issue.

**Comment by Bene-Graham** [comment]
I am also getting this issue.

It seems to occur when I do the following
```js
worksheet.dataValidations.model["B2:B1048576"] = genderValidation;
```

In versions before 3.4 it would apply the validation to all cell in that range. In version 3.4 or greater I get an error.

If i manually iterate through each cell,  it will work, but is very slow compared to how it was before.

**Comment by Siemienik** [comment]
hmm.. it's a quite dizzy situation :) We haven't documentation about `worksheet.dataValidations.model` 

I've found this PR which introduce this feature: #907 

If anyone wanna add a description to docs I will be glad

**Comment by Siemienik** [comment]
I've some investigation about that and for me, these changes are best candidates: https://github.com/exceljs/exceljs/compare/v3.3.1...v3.4.0#diff-883923368e51231ee142f6d7e9396b8bR216
