### ISSUE TITLE
Cannot set property 'outlineProperties' of null (v3.8.2)

### ISSUE THREAD

**Issue by tpkn** [exceljs/exceljs#1185]
This issue is closed https://github.com/exceljs/exceljs/issues/655, but that bug is still exists:

    TypeError: Cannot set property 'outlineProperties' of null
        at WorkSheetXform.parseClose (E:\test\parser\node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js:388:40)
        at saxStream.sax.on.node (E:\test\parser\node_modules\exceljs\lib\xlsx\xform\base-xform.js:91:21)
        at SaxesParser.closeTag (E:\test\parser\node_modules\saxes\saxes.js:2012:65)
        at SaxesParser.sCloseTag (E:\test\parser\node_modules\saxes\saxes.js:1601:18)
        at SaxesParser.write (E:\test\parser\node_modules\saxes\saxes.js:483:36)
        at SAXStream._write (E:\test\parser\node_modules\exceljs\lib\utils\sax-stream.js:11:14)
        at doWrite (_stream_writable.js:415:12)
        at writeOrBuffer (_stream_writable.js:399:5)
        at SAXStream.Writable.write (_stream_writable.js:299:11)
        at resolve (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:205:14)
        at new Promise (<anonymous>)
        at write (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:204:14)
        at Array.map (<anonymous>)
        at StreamBuf._pipe (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:210:34)
        at StreamBuf._flush (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:275:14)
        at writeComplete (E:\test\parser\node_modules\exceljs\lib\utils\stream-buf.js:288:14)

v3.8.2

**Comment by Alanscut** [comment]
@tpkn It seems to be a typo according to the code below! To let us better determine the cause of the problem, would you mind providing your file? I will submit a PR as soon as possible. 
```javascript
if (this.map.sheetPr.model && this.map.sheetPr.model.outlineProperties) {
     // outlinePropertiesx
     properties.outlineProperties = this.map.sheetPr.model.outlinePropertiesx;
}
```

**Comment by tpkn** [comment]
@Alanscut sure, here's my test file
[test.xlsx](https://github.com/exceljs/exceljs/files/4408883/test.xlsx)

**Comment by Alanscut** [comment]
@tpkn Please tell me the version of excel software you are using, because I found that the structure of the xml file in **text.xlsx** is very different from my newly created file, I can’t know if it needs to be compatible.

## For example
* The ``target``  attribute of **text.xlsx** is an absolute path and the other is a relative path.
```xml.
//  workbook.xml
<Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="/xl/worksheets/sheet1.xml" Id="rId6" />

<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml" />
```
* The **sheet1.xml ** in the newly created file should have the ```sheetFormatPr``` tag and default attributes, but the **test.xlsx** file does not have.
```xml
// sheet1.xml
 <sheetFormatPr defaultRowHeight="13.5" x14ac:dyDescent="0.15" />
````

**Comment by tpkn** [comment]
@Alanscut the whole engine that creates that xlsx files is a black box. 

Is it possible to inject `sheetFormatPr` node with manually setted attributes?

**Comment by Alanscut** [comment]
@tpkn See https://github.com/exceljs/exceljs/blob/master/README.md#worksheet-properties.

```javascript
const Excel = require('../../lib/exceljs.nodejs');

const workbook = new Excel.Workbook();
workbook.xlsx.readFile('./test.xlsx').then(function () {
  const worksheet = workbook.getWorksheet(1);
 // setting
  worksheet.properties.defaultRowHeight = 15;
  workbook.xlsx.writeFile('./target.xml').then(() => {
    console.log('ok_write')
  });
});
```

**Comment by tpkn** [comment]
@Alanscut example crashes with the same error.

**Comment by Alanscut** [comment]
@tpkn  The error is caused because there is no ``sheetFormatPr`` tag, but there are other errors. I will come up with my solution and then need to ask the authors and members of excel.js for suggestions.

@Siemienik @guyonroche any thoughts?

## Problems and solutions
1. The target attribute of **workbook.xml.rels** is an absolute path issue.
> Solutions
```javascript
// workbook.xml 
// worksheet = model.worksheetHash[`xl/${rel.Target}`];
worksheet = model.worksheetHash[`xl/${rel.Target.replace(/^(\s|\/xl\/)+/, '')}`]; 
```
2. The **sheet1.xml** in the newly created file should have the ``sheetFormatPr`` tag and default attribute.
> Solutions
```javascript
// worksheet.-xform.js
// const properties = this.map.sheetFormatPr.model; 
const properties = this.map.sheetFormatPr.model || {}; 
if (this.map.sheetPr.model && this.map.sheetPr.model.outlineProperties) {
   properties.outlineProperties = this.map.sheetPr.model.outlineProperties;
}

// sheet-format-properties-xform.js
 const attributes = {
    // defaultRowHeight: model.defaultRowHeight
    // outlineLevelRow: model.outlineLevelRow,
    // outlineLevelCol: model.outlineLevelCol,
    // 'x14ac:dyDescent': model.dyDescent,
    defaultRowHeight: model.defaultRowHeight || 15,
    outlineLevelRow: model.outlineLevelRow || 0,
    outlineLevelCol: model.outlineLevelCol || 0,
    'x14ac:dyDescent': model.dyDescent || 55,
};
```
3.  Error messag: ``Deleted record: Document subject (workbook) in **xl / workbook.xml** section``.
>Solutions
```javascript
// workbook-properties-xform.js
 render(xmlStream, model) {
    xmlStream.leafNode('workbookPr', {
      date1904: model.date1904 ? 1 : undefined,
      // defaultThemeVersion: 164011,
      defaultThemeVersion: 124226,
      filterPrivacy: 1,
   });
}
```
