### ISSUE TITLE
[BUG] Error if table doesn't have filter buttons enabled

### ISSUE THREAD

**Issue by teemue** [exceljs/exceljs#1240]
## 🐛 Bug Report

I have [this workbook](
https://drive.google.com/file/d/1KZbWavkomaX-SNoVrb7ezsV5Ws17UWDt/view?usp=sharing) with one sheet and a table in it. Using client-sided exceljs, loading the workbook causes error:
 ```
exceljs.js:22597 Uncaught (in promise) TypeError: Cannot set property 'filterButton' of undefined
    at exceljs.js:22597
    at Array.forEach (<anonymous>)
    at TableXform.parseClose (exceljs.js:22596)
    at exceljs.js:7813
    at SaxesParser.closeTag (exceljs.js:66388)
    at SaxesParser.sCloseTag (exceljs.js:65977)
    at SaxesParser.write (exceljs.js:64859)
    at SAXStream._write (exceljs.js:5852)
    at doWrite (exceljs.js:69237)
    at writeOrBuffer (exceljs.js:69226)
```
If I enable filtering buttons on the table, it doesn't cause any errors.

Lib version: 3.8.2

**Comment by teemue** [comment]
Ok it seems that it has something to do with the structured references inside the table (formulas in columns O and P. If I convert the table to a range, it works.

**Comment by dotnetshadow** [comment]
I see to have the same issue. In excel I need to go to the Data menu and turn off the Filter button

Filter on causes the error message
![image](https://user-images.githubusercontent.com/296247/156878382-5524ff87-51d2-4c0e-811c-7263b8183cfb.png)

Is there a way to ignore the filter button being enabled when reading in the workbook?

**Comment by mustafaKamal-fe** [comment]
> I see to have the same issue. In excel I need to go to the Data menu and turn off the Filter button
> 
> Filter on causes the error message ![image](https://user-images.githubusercontent.com/296247/156878382-5524ff87-51d2-4c0e-811c-7263b8183cfb.png)
> 
> ```
> c:\code\foo\node_modules\exceljs\lib\xlsx\xform\table\table-xform.js:101
>             this.model.columns[index].filterButton = column.filterButton;
>                                                    ^
> 
> TypeError: Cannot set properties of undefined (setting 'filterButton')
>     at c:\code\foo\node_modules\exceljs\lib\xlsx\xform\table\table-xform.js:101:52
>     at Array.forEach (<anonymous>)
>     at TableXform.parseClose (c:\code\foo\node_modules\exceljs\lib\xlsx\xform\table\table-xform.js:100:45)
>     at TableXform.parse (c:\code\foo\node_modules\exceljs\lib\xlsx\xform\base-xform.js:67:21)
>     at async XLSX._processTableEntry (c:\code\foo\node_modules\exceljs\lib\xlsx\xlsx.js:165:19)
>     at async XLSX.load (c:\code\foo\node_modules\exceljs\lib\xlsx\xlsx.js:391:15)
>     at async XLSX.readFile (c:\code\foo\node_modules\exceljs\lib\xlsx\xlsx.js:55:24)
> ```
> 
> Is there a way to ignore the filter button being enabled when reading in the workbook?

Same here !! 
I ahve tried inmany ways to disable filter buttons added on table headers with no effect so far: 

Following the docs, i have tried: 

`sheet.addTable({..., columns: [{name: "My header", filterButton: false}]})`

It is not working though.

**Comment by eberridge** [comment]
I'm a little late to the party but I believe I've found the root cause. Per OpenXML spec, a custom 'totalsRowFormula' in a table column will add a child element in the column XML element; however, the code in `table-column-xform.js` expects columns to be leaf nodes. As `XLSX.load()` parses the table, any such columns are not recognized by the parser and do not find their way into `this.map.tableColumns.model`. However, `this.map.autoFilter.model.columns` does have the correct number of columns. This mismatch causes a index overrun in this loop (around line 101 in table-xform.js):
```
          this.map.autoFilter.model.columns.forEach((column, index) => {
            this.model.columns[index].filterButton = column.filterButton;
          });
```

Without a fix there's no real workaround other than to remove custom totals row formulas from all tables.
