### ISSUE TITLE
[Q] Read and test attached file from response

### ISSUE THREAD

**Issue by AlexanderTeaH** [exceljs/exceljs#1463]
Hello!

I'm trying to write a test in **Jest** using **Supertest** for validating an excel file that gets generated and sent from the server like so
```js
response.status(200).attachment("Report.xlsx");
await workbook.xlsx.write(response);
```

Then I attempt to read the response in my test
```js
const response = await request.get("/generate-report");
const workbook = new excelJS.Workbook();
await workbook.xlsx.load(response.text);
```

But I get the following error
```
Corrupted zip: missing 314 bytes.
  at ZipEntries.readEndOfCentral (node_modules/jszip/lib/zipEntries.js:244:19)
  at ZipEntries.load (node_modules/jszip/lib/zipEntries.js:256:14)
  at node_modules/jszip/lib/load.js:49:20
```

I've tried a few options involving `stream`, `Buffer.from`, and creating streams to use `workbook.xlsx.read()` instead, but haven't had any luck so far. Any help would be really appreciated! 😄

**Comment by evrardts** [comment]
Hi @AlexanderTeaH have you found a solution for this issue? Facing the same here.. Thanks!

**Comment by AlexanderTeaH** [comment]
> 
> 
> Hi @AlexanderTeaH have you found a solution for this issue? Facing the same here.. Thanks!

Unfortunately not...

**Comment by duuri-mollinen** [comment]
Preventing the automated response parsing for supertest and reading the content as a buffer works for this one. ie.
```
                .buffer(true)
                .parse((res, cb) => {
                    let data = Buffer.from("");
                    res.on("data", function(chunk) {
                    data = Buffer.concat([data, chunk]);
                    });
                    res.on("end", function() {
                    cb(null, data);
                    });
                })
                .expect(async function(res) {
                    const workbook = new ExcelJS.Workbook();
                    await workbook.xlsx.load(res.body);
                  })
```
