### ISSUE TITLE
[BUG] Error opening OpenPyxl workbooks that include tables

### ISSUE THREAD

**Issue by thekevinhunt** [exceljs/exceljs#1468]
## 🐛 Bug Report

I have been encountering issues when loading spreadsheets that have been touched by OpenPyxl.  I tried digging in to find the root cause, but the best I can tell is the WorksheetModel.tables variable gets set to **tables: [ undefined ]**, which causes the following error:

> TypeError: Cannot read property 'name' of undefined
>     at /app/node_modules/exceljs/lib/doc/worksheet.js:836:20
>     at Array.reduce (<anonymous>)
>     at Worksheet.set model [as model] (/app/node_modules/exceljs/lib/doc/worksheet.js:830:32)
>     at /app/node_modules/exceljs/lib/doc/workbook.js:210:23
>     at Array.forEach (<anonymous>)
>     at Workbook.set model [as model] (/app/node_modules/exceljs/lib/doc/workbook.js:199:22)
>     at XLSX.load (/app/node_modules/exceljs/lib/xlsx/xlsx.js:395:25)
> From previous event:
>     at processImmediate (internal/timers.js:458:21)
> From previous event:
>     <calling script>

Lib version: 4.1.1
OpenPyxl version 3.0.4

## Steps To Reproduce

Problem occurs when reading a workbook; in my case via stream.

```javascript
return workbook.xlsx.read(read_stream, {'sheetName': 'Test'});
```
Attached are sample files.  Spreadsheet with table was modified by openpyxl and fails to load.  Spreadsheet without table was modified by openpyxl and loads properly.

[test file with table.xlsx](https://github.com/exceljs/exceljs/files/5242220/test.file.with.table.xlsx)
[test file 1.xlsx](https://github.com/exceljs/exceljs/files/5242221/test.file.1.xlsx)

## The expected behaviour:

Spreadsheets should be properly parsed without error.

## Possible solution (optional, but very helpful):

I got lost digging down into the parser layer of the code trying to figure out where the undefined was coming from, so the problem seems to be somewhere there.  I've not been able to figure out a meaningful difference between spreadsheets that parse properly and those that don't, put I'll keep poking at it.

As a hack, I added a conditional to the set model function in worksheet.js to verify the problem was the undefined table entry.

```javascript
      this.tables = value.tables.reduce((tables, table) => {
        table = table ? table : '';
        const t = new Table();
        t.model = table;
        tables[table.name] = t;
        return tables;
      }, {});
```

**Comment by thekevinhunt** [comment]
I've managed to pinpoint the piece of the xml that causes the issue:

xl/worksheets/_rels/sheet1.xml.rels:
`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="/x1/tables/table1.xml" Id="rId1" /></Relationships>`

Changing the target to `Target="../tables/table1.xml"` enabled Exceljs to read the file.  Given that the "bad" file opens in Excel itself without issue, I'm inclined to conclude that the bug is in Exceljs rather than OpenPyxl.

**Comment by thekevinhunt** [comment]
I have now located the issue:

In lib/xlsx/xform/book/workbook-xform.js, it appears there has been some attempt to address the issue with the target attribute.  At some point the relationship gets converted to "../":

```
      // if rel.Target start with `[space]/xl/` or `/xl/` , then it will be replaced with `''` and spliced behind `xl/`,
      // otherwise it will be spliced directly behind `xl/`. i.g.
      worksheet = model.worksheetHash[`xl/${rel.Target.replace(/^(\s|\/xl\/)+/, '')}`];
```

Then in lib/xlsx/xform/sheet/worksheet-xform.js reconcile function, the rels array includes the original /x1/ target, so the lookup to options.tables (which has the "../" change) fails:

```
      model.tables = (model.tables || []).map(tablePart => {
        const rel = rels[tablePart.rId];
        return options.tables[rel.Target];
      });
```

Potential fix (I suspect I may be oversimplifying the problem/solution, so I'm reluctant to create a push request):

lib/xlsx/xform/sheet/worksheet-xform.js|506
`return options.tables[rel.Target.replace(/^(\/x1)/, '..')];`

**Comment by taylorsamy** [comment]
Has there been any update on this?
