### ISSUE TITLE
[BUG] Error: For node versions older than 10, please use the ES5 Import

### ISSUE THREAD

**Issue by weihsth** [exceljs/exceljs#1519]
## 🐛 Bug Report

I have a NodeJS app using TypeScipt. On DEV machine all is fine, but on production, there is an error about node version and ES5 Import.

```
import { Buffer, Cell, Column, Workbook, Worksheet } from 'exceljs';

...

private _columnDefinitions: Array<Partial<Column>>;

private _columnData: any[];

private _getExcelBuffer(worksheetName: string): Promise<Buffer> {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet(worksheetName);

    worksheet.columns = this._columnDefinitions; // Array<Partial<Column>>
    worksheet.addRows(this._columnData); //  any[]

    const row = worksheet.getRow(1);

    row.font = {bold: true};

    this._autosizeColumnCells(worksheet);

    return workbook.xlsx.writeBuffer();
}

...
```

After compiling the app with Webpack to production build and running it on Ubuntu Server with NodeJS 12.18.3, I get following error:

```
Error: For node versions older than 10, please use the ES5 Import: https://github.com/exceljs/exceljs#es5-imports
     at Object.<anonymous> (/var/www/.../node_modules/exceljs/excel.js:8:9)
     at Module._compile (module.js:652:30)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.module.exports.i.__awaiter.n (/var/www/.../build/app.js:1:292421)
     at n (/var/www/.../build/app.js:1:186)
```

But I am not using NodeJS < 10.

On my DEV Windows machine with NodeJS 12.18.3, everything works just fine.

Lib version: 4.1.1

## Steps To Reproduce

See above.

## The expected behaviour:

There should not be an error about using NodeJS < 10 because i use NodeJS 12.18.3.

**Comment by weihsth** [comment]
My mistake. After running "nvm ls" I saw, that there is an older version (8.x) running to, which was used by this script.

I uninstalled the older version, which brings me to a new error:

```
for await (const chunk of stream) {
     ^^^
 SyntaxError: Unexpected reserved word
     at createScript (vm.js:80:10)
     at Object.runInThisContext (vm.js:139:10)
     at Module._compile (module.js:616:28)
     at Object.Module._extensions..js (module.js:663:10)
     at Module.load (module.js:565:32)
     at tryModuleLoad (module.js:505:12)
     at Function.Module._load (module.js:497:3)
     at Module.require (module.js:596:17)
     at require (internal/module.js:11:18)
     at Object.<anonymous> (/var/www/.../node_modules/exceljs/lib/doc/workbook.js:5:14)

```

**Comment by weihsth** [comment]
I use the es5 modules until I found out, why there is a node version 8.x for my node process, but nvm ls is not listing this version...

this is a workaround:
```
require('core-js/modules/es.promise');
require('core-js/modules/es.string.includes');
require('core-js/modules/es.object.assign');
require('core-js/modules/es.object.keys');
require('core-js/modules/es.symbol');
require('core-js/modules/es.symbol.async-iterator');
require('regenerator-runtime/runtime');

const ExcelJS = require('exceljs/dist/es5');
```
