### ISSUE TITLE
[BUG] problem with exports modules 

### ISSUE THREAD

**Issue by saulomano** [exceljs/exceljs#1542]
## 🐛 Bug Report

I have problem when using library in testing server. The library  works well in  local environment on S.O ubuntu. My test server is Amazon Ami 2, with same version of nodejs , npm.

I try with node version 13,  v14.2.0  it's same issue.

/home/ec2-user/software/accountingwebserver/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1050:16)
    at Module._compile (internal/modules/cjs/loader.js:1098:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ec2-user/software/accountingwebserver/node_modules/exceljs/lib/xlsx/xform/sheet/cf-ext/cf-rule-ext-xform.js:1:22)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)

Lib version: "exceljs": "^4.2.0",

## Steps To Reproduce
Include library in project

`const excel = require('exceljs');`

and execute `node index` for start express framework

## Possible solution (optional, but very helpful):

update node version to v14.15.1

```javascript

```

**Comment by mormazabal** [comment]
rm -rf node_modules/
npm install

works for me!

**Comment by cgiontrading** [comment]
Upgrading to "uuid" 9.0.0 should resolve this issue. I have same issue with the jest testing library.
please check https://github.com/uuidjs/uuid/issues/451 for details.

**Comment by houseofyin** [comment]
I ran into this too when upgrading Jest.  Jest noted this issue with some other libraries ( https://jest-archive-august-2023.netlify.app/docs/28.x/upgrading-to-jest28/ ) and referenced this discussion:  https://github.com/microsoft/accessibility-insights-web/pull/5421#issuecomment-1109168149  I found I was able to avoid the errors in some tests by forcing a node test environment, but that of course doesn't work when testing browser components that use this library.
