### ISSUE TITLE
[BUG] Read xlsx file

### ISSUE THREAD

**Issue by Shenor** [exceljs/exceljs#1559]
## Error reading xlsx file

Lib version: 4.2.0

## Steps To Reproduce

```javascript
(async () => {
    const Excel = require('exceljs');
    const workbook = new Excel.Workbook();
    const file = await workbook.xlsx.readFile('./template/excel-template.xlsx');
    console.log(file)
})();
```
When I try to read the xlsx file, I get this error

```javascript
(node:6324) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'anchors' of undefined
    at DrawingXform.reconcile (C:\Users\Username\Desktop\generate-score\node_modules\exceljs\lib\xlsx\xform\drawing\drawing-xform.js:94:11)
    at C:\Users\Username\Desktop\generate-score\node_modules\exceljs\lib\xlsx\xlsx.js:109:22
    at Array.forEach (<anonymous>)
    at XLSX.reconcile (C:\Users\Username\Desktop\generate-score\node_modules\exceljs\lib\xlsx\xlsx.js:92:33)
    at XLSX.load (C:\Users\Username\Desktop\generate-score\node_modules\exceljs\lib\xlsx\xlsx.js:411:10)
    at async XLSX.readFile (C:\Users\Username\Desktop\generate-score\node_modules\exceljs\lib\xlsx\xlsx.js:55:24)
    at async C:\Users\Username\Desktop\generate-score\index.js:4:18
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit 
code.
```

**Comment by Moussawi7** [comment]
I have the same issue on a protected file, but it is working fine on an unprotected file.

**Comment by sgestin** [comment]
I had this issue when in drawings folder I had a drawing which is of type c:userShapes. In this case, model used in DrawingXform is undefined and this generate the exception.

This needs correction.

**Comment by zmatez** [comment]
Same here, trying to read file with "protected view". Works when you manually allow editing on Excel.
