### ISSUE TITLE
[BUG] addRow() not adding merged cells correctly which are read from source file

### ISSUE THREAD

**Issue by aksharj** [exceljs/exceljs#1567]
Hi All,

I am trying to read from a excel file, manipulate some data and write to another excel. I am seeing a weird issue when adding rows which have merged cells. They are not getting added as expected in the destination file, the rows are appearing non-merged.

Below is the relevant part of the code. I am using `streams` and `addRow`.

```
const readerOptions = {
sharedStrings: 'cache',
 hyperlinks: 'cache',
 worksheets: 'emit',
 styles: 'cache',
};
const writerOptions = {
 filename: fpath,
 useStyles: true,
 useSharedStrings: true
}
const workbook = new ExcelJS.stream.xlsx.WorkbookWriter(writerOptions)
const myworksheet = workbook.addWorksheet('Sheet 1');
const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(sheet.path, readerOptions);
workbookReader.read();
workbookReader.on('worksheet', worksheet => {
 worksheet.on('row', row => {
  const r = myworksheet.addRow();
  Object.assign(r, row);
 });
});

workbookReader.on('end', async () => {
 await workbook.commit();
});
```

Please find the below images for your reference. expected_result.png and actual_result.png

<img width="706" alt="actual_result" src="https://user-images.githubusercontent.com/8026629/102329976-4b389180-3f89-11eb-986c-714cb571406a.png">
<img width="706" alt="expected_result" src="https://user-images.githubusercontent.com/8026629/102329981-4c69be80-3f89-11eb-9982-8849f6049a00.png">

Any help on how to fix this will be really great, Thanks.

**Comment by aksharj** [comment]
@Siemienik tagging for help.

**Comment by aksharj** [comment]
HI,

Just an update from my side. I have tried with the below code but i still do not seem to get the rows with merged cells to copy correctly


```
const readerOptions = {
  sharedStrings: 'cache',
  hyperlinks: 'cache',
  worksheets: 'emit',
  styles: 'cache',
};
const writerOptions = {
 filename: fpath,
 useStyles: true,
 useSharedStrings: true
}
const workbook = new ExcelJS.stream.xlsx.WorkbookWriter(writerOptions)
  const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(sheet.path, readerOptions);
  const myworksheet = workbook.addWorksheet('Sheet 23');
  for await (const worksheetReader of workbookReader) {
    for await (const row of worksheetReader) {
      const r = myworksheet.addRow();
      Object.assign(r, row);
    }
  }
await workbook.commit();
```

**Comment by aksharj** [comment]
Hi, any help on how to fix this will be really great. running out of ideas as to how to fix this. 
 I am ready to work on a PR as well can someone please point me in the correct direction?

Thanks.

**Comment by aksharj** [comment]
@alubbe tagging for help

**Comment by aksharj** [comment]
If i try to merge cells by hardcoding, i get the error `Cannot merge already merged cells`. But the cells in the excel do not appear to be merged

```
Error: Cannot merge already merged cells
    at /node_modules/exceljs/lib/stream/xlsx/worksheet-writer.js:438:15
    at Array.forEach (<anonymous>)
    at WorksheetWriter.mergeCells (/node_modules/exceljs/lib/stream/xlsx/worksheet-writer.js:436:18)
    at WorksheetReader.<anonymous> (/lib/excel/transformer.js:55:27)
    at WorksheetReader.emit (events.js:310:20)
    at WorksheetReader.EventEmitter.emit (domain.js:482:12)
    at WorksheetReader.read (/node_modules/exceljs/lib/stream/xlsx/worksheet-reader.js:96:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WorkbookReader.read (/node_modules/exceljs/lib/stream/xlsx/workbook-reader.js:57:13)
```

**Comment by Siemienik** [comment]
Probably I can't help you because of the lack of time to investigate it deeply. However my will you try to use non-stream API?

**Comment by aksharj** [comment]
hi @Siemienik thanks for your reply. Actually, excel files in some case might be large that's the reason i need to use streams.

I have found a workaround, i am checking if the row has merged cells and then merge it again after adding rows.  The way i am checking if rows contain merged cells is as follows.

```
if((newRow.actualCellCount !== newRow.cellCount) && (newRow.actualCellCount == 1)) {
```

Do you think the above way makes sense or may be there might be a better way to detect if rows has merged cells.

Full relevant code to copy excel is as follows.
```
        const workbook = new ExcelJS.stream.xlsx.WorkbookWriter(writerOptions);
        const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(sheet.path, readerOptions);
        const myworksheet = workbook.addWorksheet('Sheet 1');
        workbookReader.read();
        workbookReader.on('worksheet', worksheet => {
          worksheet.on('row', row => {
            const newRow = myworksheet.addRow();
            Object.assign(newRow, row);
            if((newRow.actualCellCount !== newRow.cellCount) && (newRow.actualCellCount == 1)) {
              let cellLength = newRow.model.cells.length;
              myworksheet.mergeCells(`${newRow.model.cells[0].address}:${newRow.model.cells[cellLength - 1].address}`)
            }
          });
        });

```

Do let me know if this makes sense or may be better way to achieve this, for now this works for me.

Thanks.

**Comment by Siemienik** [comment]
Probably, your problem follows from that, when `on('worksheet',...)` is called, then not all rows are read. That means. the worksheet object hasn't full knowledge about its model.

I'm happy that your code works :+1:

**Comment by eug-vs** [comment]
Hi! Could this be related to #292? My use-case is duplicating rows: currently duplicating a row with merged cells results into a row with all cells unmerged. I've came up with a workaround (it assumes that row you're duplicating only contains merged cells within itself, i.e no cell in this row is merged with other rows):
```typescript
const duplicateRowWithMergedCells = (sheet: any, row: number, count: number) => {
  sheet.duplicateRow(row, count, true);

  const merges: string[] = sheet.model.merges;
  // Find all merges inside initial row
  const rowMerges = merges.filter(range => range.match(`\\w+${row}:\\w+${row}`));

  _.times(count, index => {
    const newRow = row + index + 1;

    // Unmerge everything in a newRow so we dont run into conflicts
    merges
      .filter(range => range.match(`\\w+${newRow}:\\w+${newRow}`))
      .forEach(range => sheet.unMergeCells(range));

    // Merge the same cells as in the initial row
    rowMerges
      .map(range => range.replace(new RegExp(`${row}`, 'g'), `${newRow}`))
      .forEach(range => sheet.mergeCells(range));
  });
};
```
>Do you think the above way makes sense or may be there might be a better way to detect if rows has merged cells.

@aksharj note how I unmerge rows before manually transferring new merges. I think this answers you question.


I did not dive deep into the library, but my understanding of this part of the bug is: when duplicating a row with `insert = true` (and maybe in other scenarios) it does not remove old merges from cells which were previously on the positions where are you inserting. Therefore you can run into conflicts sometimes.

**Comment by MGber** [comment]
Hello ExcelJS community,

I wanted to share a solution I implemented to handle the challenge of inserting rows in Excel files with merged cells. As many of you might know, managing merged cells during row insertions can be tricky, and I didn't find a built-in method in ExcelJS that handles this seamlessly.

Overview of the Solution:

1) Unmerge Cells: Initially, all merged cells are unmerged to simplify the insertion process.
2) Track Indices: The system keeps track of the indices of the originally merged cells to remember their initial state.
3) Handle Insertions/Deletions: When adding or removing rows, the indices are adjusted accordingly to maintain data consistency.
4) Duplicating Rows with Merged Cells: To duplicate a row with merged cells, simply insert a new row and transpose in the system the merges from the row to be duplicated to the new row.
5) Re-merge Cells: After the modifications are complete, cells are re-merged based on their original state using the tracked indices.

While I can't share the enterprise-specific code, I hope this high-level overview provides some guidance or inspiration for those facing a similar challenge. If anyone has further questions or would like more details on the logic, I'd be happy to discuss !

To accès the merges in TypeScript was something like : 
`const merges = ((sheet.model) as any).merges;`

Best regards, Maxime Gaber.

**Comment by MGber** [comment]
I've addressed the bug topic in this comment: [link](https://github.com/exceljs/exceljs/issues/1567#issuecomment-1677355538).

**Comment by tdr2d** [comment]
Hello,
I faced this issue as well, I also wanted to add rows and keep the merging model at the same time.
Adding a new row also breaks the merging model of the rows underneath.
So, I ended up **not using merged cells, rather centering data horizontally on multiple cells**: [https://kb.wisc.edu/helpdesk/page.php?id=119089](https://kb.wisc.edu/helpdesk/page.php?id=119089)

**Comment by imfurankase** [comment]
If you're facing issues with merged cells when inserting new rows using ExcelJS, here's a clear approach on how i handled this:

1. **Problem Recap**: ExcelJS may not automatically retain the merged state when inserting rows that involve merged cells, leading to conflicts and errors like "Cannot merge already merged cells."

2. **Solution Overview**: To handle this, we recommend(just in case):
   - **Unmerging Cells Temporarily**: Before inserting or duplicating rows, ensure all cells in the range are unmerged.
   - **Tracking Merged Cells**: Keep track of the original merged cell ranges.
   - **Re-merging Cells After Modifications**: After inserting or duplicating rows, use the tracked ranges to re-merge the cells.

3. **Utility Function Approach**: We created a utility function to check if cells in a range are already merged and merge them if needed. This function avoids merging cells that are already merged and handles merging cells dynamically.

### Example Code:

**Utility Function (`mergeCellsIfNeeded`)**:
```typescript
import ExcelJS from "exceljs";

/**
 * Merges cells in a given range if they are not already merged.
 *
 * @param worksheet - The ExcelJS worksheet object.
 * @param range - The cell range to merge, e.g., "A1:C3".
 */
export const mergeCellsIfNeeded = (
  worksheet: ExcelJS.Worksheet,
  range: string
) => {
  const [startCell, endCell] = range.split(":");
  const startRow = worksheet.getCell(startCell).row;
  const endRow = worksheet.getCell(endCell).row;
  const startCol = worksheet.getCell(startCell).col;
  const endCol = worksheet.getCell(endCell).col;

  let alreadyMerged = false;

  for (let row = startRow; row <= endRow; row++) {
    for (let col = startCol; col <= endCol; col++) {
      const cell = worksheet.getCell(row, col);
      if (cell.isMerged) {
        alreadyMerged = true;
        break;
      }
    }
    if (alreadyMerged) break;
  }

  if (!alreadyMerged) {
    worksheet.mergeCells(range);
  }
};
```

**Usage in Your Code**:
```typescript
import ExcelJS from "exceljs";
import { mergeCellsIfNeeded } from "src/utils/excelUtils";

export const modifyExcelSheet = async () => {
  const templateUrl = "/templates/example.xlsx"; // Your template path here

  try {
    // Load the template workbook
    const response = await fetch(templateUrl);
    const data = await response.arrayBuffer();
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(data);

    const worksheet = workbook.getWorksheet(1);

    if (!worksheet) {
      console.error("Worksheet not found in the Excel file.");
      return;
    }

    // Merge cells if they are not already merged
    mergeCellsIfNeeded(worksheet, "A1:C1");
    worksheet.getCell("A1").value = "Merged Header";

    // Add new rows with merged cells
    const newRowNumber = worksheet.lastRow.number + 1;
    worksheet.insertRow(newRowNumber, ["Data1", "Data2", "Data3"]);
    mergeCellsIfNeeded(worksheet, `A${newRowNumber}:C${newRowNumber}`);
    worksheet.getCell(`A${newRowNumber}`).value = "Merged Row Data";

    // Save the modified workbook
    const buffer = await workbook.xlsx.writeBuffer();
    const blob = new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    });

    saveAs(blob, "ModifiedExample.xlsx");
  } catch (error) {
    console.error("Error modifying Excel file:", error);
  }
};
```

**Comment by CJxD** [comment]
I opted to update the merge model in the worksheet which seems to do the trick for me.

In my case, my xlsx template contained merged cells underneath a table whose rows were due to be duplicated, but where these merged cells are is not known ahead of time.

The approach is to loop through the private `worksheet._merges` object and add (or subtract) the same number of rows to the range as the number of rows inserted above.

```typescript
function moveMergesModel(
  worksheet: ExcelJS.Worksheet,
  afterRow: number,
  numRows: number,
) {
  // @ts-ignore - _merges is a private property
  const merges = worksheet._merges as { [cell: string]: ExcelJS.Range };
  // @ts-ignore - _merges is a private property
  worksheet._merges = Object.fromEntries(
    // Loop through each of the ranges in the merges map
    Object.entries(merges).map(([cell, range]) => {
      // If the range is below the target row, return it as is
      if (range.top <= afterRow) {
        return [cell, range];
      }
      // Otherwise, move the precached merge range down by numRows
      // This also works for negative numbers if rows were deleted
      range.top += numRows;
      range.bottom += numRows;
      // Update the name of the map entry to the new top-left cell name
      const newTopLeftCell = worksheet.getCell(range.top, range.left).address;
      return [newTopLeftCell, range];
    }),
  );
}

// Example usage
const workbook = new ExcelJS.Workbook();
const worksheet = workbook.getWorksheet(1);
const rowToDuplicate = 5;
const rowsToAdd = 10;
worksheet.duplicateRow(rowToDuplicate, rowsToAdd, true);
moveMergesModel(worksheet, rowToDuplicate, rowsToAdd);
```

@Siemienik @mikez perhaps this strategy can be used in `spliceRows` in https://github.com/exceljs/exceljs/blob/5bed18b45e824f409b08456b59b87430ded023ab/lib/doc/worksheet.js#L486 ?

**Comment by IonelLupu** [comment]
I am still getting `Cannot merge already merged cells` even after using the `moveMergesModel` helper above. 😞  I even used [this approach](https://github.com/exceljs/exceljs/discussions/1967#discussioncomment-2172573) of unmerging the cells before merging them. Getting the same error. 

What can be done?

**Comment by dolphinxx** [comment]
> I am still getting `Cannot merge already merged cells` even after using the `moveMergesModel` helper above. 😞 I even used [this approach](https://github.com/exceljs/exceljs/discussions/1967#discussioncomment-2172573) of unmerging the cells before merging them. Getting the same error.
> 
> What can be done?

Don't use `worksheet.mergeCells()`, because the `_merges` is not updated when inserting/deleting rows. Instead use `cell.merge(masterCell, ignoreStyle)` , which does not check the merge status via `_merges`.

**Comment by cjnoname** [comment]
It's fixed in here
https://www.npmjs.com/package/@cj-tech-master/excelts

**Comment by tdr2d** [comment]
Hello,

Using version 4.4.0, [@CJxD ](https://github.com/exceljs/exceljs/issues/1567#issuecomment-2374347682) fix did not work for me, I found this following solution.
I simply delete ALL the old keys in sheet._merges before, then I call sheet.mergeCells on the new cell coordinates.


```javascript
function update_merged_cells(sheet, start_row, added_rows) {
    // Update Merged cells after start_row when inserting new rows (do not fix merged cells when inserting columns)
    if (added_rows == 0) { return }
    let cell_to_remerge = []
    for (const key of Object.keys(sheet._merges)) {
        let cell = sheet._merges[key];
        if (cell.top >= start_row) {
            cell_to_remerge.push({'top': cell.top + added_rows, 'bottom': cell.bottom + added_rows, 'left': cell.left, 'right': cell.right});
            delete sheet._merges[key];
        }
    }

    for (const range of cell_to_remerge) {
        sheet.mergeCells(range.top, range.left, range.bottom, range.right);
    }
}
```

How I use it :
This will shift the merging of the cells that was defined initially starting row 20, if you inserted `offset` rows before row 20.
```javascript
update_merged_cells(sheet, 20, offset) 
```

Or anytime you insert a row
```javascript
const new_row = sheet.insertRow(rowIndex, row_ref._cells.map(x => zoneDescription));
update_merged_cells(sheet, rowIndex, 1)
```
