### ISSUE TITLE
[BUG] conditional formatting rule has formulae == undefined

### ISSUE THREAD

**Issue by bno1** [exceljs/exceljs#1751]
## 🐛 Bug Report

I'm working with some excel sheets and I get an error when trying to save a file:

```
(node:12712) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at CfRuleXform.renderExpression (project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:158:55)
    at CfRuleXform.render (project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:122:14)
    at project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:29:25
    at Array.forEach (<anonymous>)
    at ConditionalFormattingXform.render (project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:26:17)
    at project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:41:20
    at Array.forEach (<anonymous>)
    at ConditionalFormattingsXform.render (project/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:40:11)
    at WorkSheetXform.render (project/node_modules/exceljs/lib/xlsx/xform/sheet/worksheet-xform.js:329:36)
    at project/node_modules/exceljs/lib/xlsx/xlsx.js:562:22
    at Array.forEach (<anonymous>)
    at XLSX.addWorksheets (project/node_modules/exceljs/lib/xlsx/xlsx.js:560:22)
    at XLSX.write (project/node_modules/exceljs/lib/xlsx/xlsx.js:654:16)
```
This happens because `model.formulae` is undefined in `renderExpression` in `cf-rule-xform.js`.

I looked in tho the sheet xml structure and found the following definition for the node that causes problems:
```xml
  <extLst>
    <ext xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" uri="{78C0D931-6437-407d-A8EE-F0AAD7539E65}">
      <x14:conditionalFormattings>
        <x14:conditionalFormatting xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
          <x14:cfRule type="expression" priority="65" id="{A28818B6-F042-4DD8-A7ED-39EDFCFB773F}">
            <xm:f>Raport!$H$13=""</xm:f>
            <x14:dxf>
              <font>
                <color rgb="FFFFFFFF"/>
              </font>
            </x14:dxf>
          </x14:cfRule>
          <xm:sqref>AO64:AQ64</xm:sqref>
```

This seems to be part of this schema: https://docs.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/025ea6e4-ad42-43ea-a016-16f4e4688ac8, where `cfRule` nodes have the formula in the `<xm:f>` tag instead of `<formula>`.

Lib version: 4.2.1

## Steps To Reproduce

```javascript
const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile('./example_report.xlsx');
await workbook.xlsx.writeFile('out_report.xlsx');
```

## The expected behaviour:

File to be written successfully

## Possible solution (optional, but very helpful):

Implement the needed schema I think

**Comment by miraks31** [comment]
I have the same issue.

**Comment by FutureFluent** [comment]
Still hitting this on `exceljs@4.4.0` with the EFRAG VSME Digital Template v1.1.0 — a publicly downloadable Excel template used by EU SMEs for the new VSME sustainability disclosure standard ([efrag.org](https://www.efrag.org/)). Same stack as the original report: `renderExpression` → `model.formulae[0]` undefined at `cf-rule-xform.js:158`.

The closed #2311 has the same root cause, a one-line fix proposed (`model.formulae?.[0]`), and a community PR from @AndresDSoto. @ericLemanissier already asked to reopen #2311. Adding our voice — this currently blocks VSME report export for every SME using the official EFRAG template through ExcelJS.

Workaround for anyone landing here: walk every cell after populating data and replace formula cells with their cached evaluated result before `writeBuffer()`:

```js
workbook.eachSheet(sheet => {
  sheet.eachRow({ includeEmpty: true }, row => {
    row.eachCell({ includeEmpty: true }, cell => {
      try {
        if (cell.type === ExcelJS.ValueType.Formula) {
          cell.value = cell.value?.result ?? null;
        }
      } catch { /* skip individual bad cells */ }
    });
  });
});
```

Note: don't read `cell.formula` itself in this sweep — the getter calls `slideFormula` which throws on shared-formula cells whose master coord can't be resolved. `cell.type` and `cell.value` are safe.
