### ISSUE TITLE
Error parsing - 0.2.9 to 0.2.10

### ISSUE THREAD

**Issue by Orvisky** [exceljs/exceljs#178]
When we switched between version 0.2.9 to 0.2.10, this parse error occured:

```
.../node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:89
              throw new Error('Unexpected xml node in parseOpen: ' + JSON.stringify(node));
              ^

    Error: Unexpected xml node in parseOpen: {"name":"dc:title","attributes":{},"isSelfClosing":false}
        at utils.inherits.parseOpen (.../node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:89:17)
        at SAXStream.<anonymous> (.../node_modules/exceljs/lib/xlsx/xform/base-xform.js:65:14)
        at emitOne (events.js:77:13)
        at SAXStream.emit (events.js:169:7)
        at Object.me._parser.(anonymous function) [as onopentag] (.../node_modules/sax/lib/sax.js:245:15)
        at emit (.../node_modules/sax/lib/sax.js:615:33)
        at emitNode (.../node_modules/sax/lib/sax.js:620:3)
        at openTag (.../node_modules/sax/lib/sax.js:801:3)
        at Object.write (.../node_modules/sax/lib/sax.js:1169:26)
        at SAXStream.write (.../node_modules/sax/lib/sax.js:227:16)
        at Entry.ondata (_stream_readable.js:542:20)
        at emitOne (events.js:77:13)
        at Entry.emit (events.js:169:7)
        at readableAddChunk (_stream_readable.js:153:18)
        at Entry.Readable.push (_stream_readable.js:111:10)
        at Entry.Transform.push (_stream_transform.js:128:32)
```
- this error is throwing all version from 2.0.10

**Comment by guyonroche** [comment]
@Orvacko,  Could you attach a sample xlsx file that shows this?

**Comment by Orvacko** [comment]
Here is the file [https://www.dropbox.com/s/y7q8nnfx9168tqp/report.xlsx?dl=0](https://www.dropbox.com/s/y7q8nnfx9168tqp/report.xlsx?dl=0)

**Comment by stavenko** [comment]
Are there any fixes to this? Still getting the same on version 0.2.29

```

Error: Unexpected xml node in parseOpen: {"name":"dc:title","attributes":{},"isSelfClosing":false}
    at utils.inherits.parseOpen (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\lib\xlsx\xform\core\core-xform.js:89:17)
    at SAXStream.<anonymous> (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\lib\xlsx\xform\base-xform.js:65:14)
    at emitOne (events.js:77:13)
    at SAXStream.emit (events.js:169:7)
    at Object.SAXStream.on.me._parser.(anonymous function) [as onopentag] (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:245:15)
    at emit (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:615:33)
    at emitNode (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:620:3)
    at openTag (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:801:3)
    at Object.write (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:1169:26)
    at SAXStream.write (C:\Users\vstavenko\projects\SecureProject\node_modules\exceljs\node_modules\sax\lib\sax.js:227:16)
    at Entry.ondata (_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at Entry.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Entry.Readable.push (_stream_readable.js:111:10)
    at Entry.Transform.push (_stream_transform.js:128:32)
```

Here's `core.xml` file contents:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dc:title>Untitled</dc:title>
    <dc:subject></dc:subject>
    <dc:creator>Talented Man</dc:creator>
    <cp:keywords></cp:keywords>
    <dc:description></dc:description>
    <cp:lastModifiedBy>Talented Man</cp:lastModifiedBy>
    <dcterms:created xsi:type="dcterms:W3CDTF">2014-02-06T10:53:56Z</dcterms:created>
    <dcterms:modified xsi:type="dcterms:W3CDTF">2016-09-14T13:28:49Z</dcterms:modified>
    <cp:category></cp:category>
</cp:coreProperties>

```

**Comment by stavenko** [comment]
@joeSaad Try to explore document in file browser and look for the contents of displayed file. In my case I unzipped xlsx file and content of the folder, searching for xml tags, that displayed in node exception (e.g. "dc:title").
And you better give certain exception occurred.

**Comment by Siemienik** [comment]
it seems be resolved
