### ISSUE TITLE
[BUG] Cannot assign to read only property 'alignment' of object '#<Object>' 

### ISSUE THREAD

**Issue by bug249286** [exceljs/exceljs#1813]
## 🐛 Bug Report
```

[Nest] 6   - 08/14/2021, 11:01:19 PM   [RpcExceptionsHandler] Cannot assign to read only property 'alignment' of object '#<Object>' +9920ms
TypeError: Cannot assign to read only property 'alignment' of object '#<Object>'
    at Cell.set alignment [as alignment] (/usr/src/app/node_modules/exceljs/lib/doc/cell.js:72:26)

```
Lib version: 4.2.1

## Steps To Reproduce

```
const workbook = new ExcelJS.Workbook();
await workbook.xlsx.readFile('./template-data.xlsx');
let sheet = workbook.getWorksheet('Sheet1');
sheet.insertRows(4,items, 'o+');
sheet.getCell('C4').alignment = {
                    vertical: 'middle',
                    horizontal: 'left',
                    wrapText: true,
                  };
```

Error :
```

[Nest] 6   - 08/14/2021, 11:01:19 PM   [RpcExceptionsHandler] Cannot assign to read only property 'alignment' of object '#<Object>' +9920ms
TypeError: Cannot assign to read only property 'alignment' of object '#<Object>'
    at Cell.set alignment [as alignment] (/usr/src/app/node_modules/exceljs/lib/doc/cell.js:72:26)


```
How to fix.

Thank you.

**Comment by SyedaliMsa** [comment]
I guess you need to assign row in const and try to assign based on row.

let sheet = workbook.getWorksheet('Sheet1');
Const tempRowName=sheet.insertRows(4,items, 'o+');
tempRowName.getCell('C4').alignment = {
                    vertical: 'middle',
                    horizontal: 'left',
                    wrapText: true,
                  };

**Comment by kaisprites** [comment]
Did you include a definition of `Object.prototype.alignment` on your project? I suffered similar problem on property 'log' when I have `Object.prototype.log = input => {console.log(input); return input;}` on my project. The problem is solved when remove this.

**Comment by ikzhr** [comment]
When a row is inserted with inherited style, the style seems to be immutable.
https://github.com/exceljs/exceljs/blob/master/lib/doc/worksheet.js#L412
(`insertRows` calls `_copyStyle` internally)

I don't know the intent of `Object.freeze` being applied, but I think the style needs to be deep-copied in this situation like [here](https://github.com/exceljs/exceljs/blob/master/lib/doc/row.js#L411:L411).

**Comment by maganap** [comment]
@Siemienik I know this case is closed but I'm currently getting errors trying to edit border and alignment of cells in rows that inherited style.  `exceljs@4.3.0`

```ts
TypeError: Cannot assign to read only property 'alignment' of object '[object Object]'

and

TypeError: Cannot assign to read only property 'border' of object '[object Object]'
```

This is typescript. Not sure whether it should complain about `ExcelJS.Cell` instead of just `Object`. Maybe that's related to the problem.

I re-created the styles for the row (instead of inheriting) and it raises no issues.
