### ISSUE TITLE
[BUG] Invalid string length

### ISSUE THREAD

**Issue by Coande** [exceljs/exceljs#1868]
## 🐛 Bug Report

Lib version: 4.3.0

## Steps To Reproduce

I have a large xlsx file export by third part system, has 153MB.

Use:

```
const workbook = new Excel.Workbook();
await workbook.xlsx.readFile(file);
const worksheet = workbook.worksheets[0];
const row = worksheet.getRow(1);
console.log(row.values);
```

Error:

```
(node:4584) UnhandledPromiseRejectionWarning: RangeError: Invalid string length
    at Array.join (<anonymous>)
    at concat (C:\Users\Coande\Desktop\excel-to-db\node_modules\exceljs\node_modules\jszip\lib\stream\StreamHelper.js:51:30)
    at StreamHelper.<anonymous> (C:\Users\Coande\Desktop\excel-to-db\node_modules\exceljs\node_modules\jszip\lib\stream\StreamHelper.js:96:61)
    at Immediate.<anonymous> (C:\Users\Coande\Desktop\excel-to-db\node_modules\exceljs\node_modules\jszip\lib\utils.js:381:18)
    at processImmediate (internal/timers.js:464:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## The expected behaviour:

Read file normally.

## Possible solution (optional, but very helpful):

I don't know.

**Comment by asherklein** [comment]
Hi @Coande ! I got the same issue, how did you solve it?

**Comment by Coande** [comment]
Not solve it yet. Also with this issue https://github.com/exceljs/exceljs/issues/1864 , I replace it to [xlsx-extract](https://github.com/ffalt/)

**Comment by kipertech** [comment]
I encountered this bug yesterday, and I believe that having the large Excel file caused this. My Excel file was having 1 million rows, I split it into 2 files and it worked perfectly again.

**Comment by YuzeLou** [comment]
I changed the code in xlsx.js from line 302 to the following and it worked:

```typescript
content = await entry.async('nodebuffer'); // Get content as Node.js Buffer
const chunkSize = 16 * 1024; // 16 KB
for (let i = 0; i < content.length; i += chunkSize) {
    const chunk = content.slice(i, i + chunkSize);
    stream.write(chunk);
}
```

**Comment by maoxian-1** [comment]
> I changed the code in xlsx.js from line 302 to the following and it worked:
> 
> content = await entry.async('nodebuffer'); // Get content as Node.js Buffer
> const chunkSize = 16 * 1024; // 16 KB
> for (let i = 0; i < content.length; i += chunkSize) {
>     const chunk = content.slice(i, i + chunkSize);
>     stream.write(chunk);
> }

It's working, but will cause some data missing
