### ISSUE TITLE
[BUG] I am getting below issue is there anything wrong i am doing here?

### ISSUE THREAD

**Issue by prashantrbs** [exceljs/exceljs#1943]
## 🐛 Bug Report

I am trying to understand how it works. i have created sample.js file for write operation and when i run i got below isssu please assit

Lib version: Latest

## Steps To Reproduce

Code:
// construct a streaming XLSX workbook writer with styles and shared strings
const options = {
    filename: './streamed-workbook.xlsx',
    useStyles: true,
    useSharedStrings: true
  };
  const workbook = new Excel.stream.xlsx.WorkbookWriter(options);
  
  worksheet.addRow({
    id: i,
    name: theName,
    etc: someOtherDetail
 }).commit();

 const workbook = new Excel.stream.xlsx.WorkbookWriter(options);
                   ^
ReferenceError: Excel is not defined
    at Object.<anonymous> (/home/prashant/VWork/write.js:7:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

**Comment by hardikdiyora** [comment]
you need to import the module. 

for example,
const Excel = require('exceljs')
