### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'richText')

### ISSUE THREAD

**Issue by vaynevayne** [exceljs/exceljs#2220]
"exceljs": "^4.3.0",
```
exceljs.min.js:3 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'richText')
    at u.value (exceljs.min.js:3:1)
    at a.value (exceljs.min.js:3:1)
    at exceljs.min.js:3:1
    at Array.forEach (<anonymous>)
    at u.value (exceljs.min.js:3:1)
    at exceljs.min.js:3:1
    at Array.forEach (<anonymous>)
    at u.value (exceljs.min.js:3:1)
    at u.value (exceljs.min.js:3:1)
    at exceljs.min.js:3:1
    at Array.forEach (<anonymous>)
    at t.value (exceljs.min.js:3:1)
    at t.<anonymous> (exceljs.min.js:3:1)
    at f (exceljs.min.js:17:1)
    at Generator._invoke (exceljs.min.js:17:1)
    at Generator.next (exceljs.min.js:17:1)
    at i (exceljs.min.js:3:1)
    at s (exceljs.min.js:3:1)
    at exceljs.min.js:3:1
    at new Promise (<anonymous>)
    at t.<anonymous> (exceljs.min.js:3:1)
    at t.<anonymous> (exceljs.min.js:3:1)
    at t.<anonymous> (exceljs.min.js:3:1)
    at f (exceljs.min.js:17:1)
    at Generator._invoke (exceljs.min.js:17:1)
    at Generator.next (exceljs.min.js:17:1)
    at i (exceljs.min.js:3:1)
    at s (exceljs.min.js:3:1)
    at exceljs.min.js:3:1
    at new Promise (<anonymous>)
    at t.<anonymous> (exceljs.min.js:3:1)
    at t.<anonymous> (exceljs.min.js:3:1)
    at saveWorkbook (shared.ts:12:1)
    at _callee$ (MultiHeader.ts:68:1)
    at tryCatch (runtime.js:45:1)
    at Generator.invoke [as _invoke] (runtime.js:274:1)
    at prototype.<computed> [as next] (runtime.js:97:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
```

**Comment by robertmiddlekauffmckinsey** [comment]
I am also getting this error

**Comment by 0xSharp** [comment]
Same
