### ISSUE TITLE
Unexpected node in parseOpen

### ISSUE THREAD

**Issue by Cosrnos** [exceljs/exceljs#227]
I'm trying to open a workbook using exceljs and I'm running into this problem when trying to parse the document

```
Error: Unexpected xml node in parseOpen: {"name":"dc:identifier","attributes":{},"isSelfClosing":true}
    at parseOpen (/project/node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:107:17)
    at SAXStream.<anonymous> (/project/node_modules/exceljs/lib/xlsx/xform/base-xform.js:65:14)
```

It doesn't seem to be an invalid document as other programs have no problem opening the document. I'm wondering if there's something missing?

Here's my code

```
      var workbook = new Excel.Workbook();
      return workbook.xlsx.readFile(__dirname + '/../../test.xlsx').then(function (wb) {
        console.log('wb');
      }).catch(reject);
```

**Comment by SeNaP** [comment]
Try open File -> Information and right tible you can show Properties, click show more properties then add Organization name = Microsoft Corporation

This is helped me.

**Comment by Cosrnos** [comment]
I was able to coerce exceljs to work with the document. It seems there's an incompatibility with documents created by openpyxl & XNML style

**Comment by jorgepinon** [comment]
I have a similar problem with 2 different files. How can I tell if it's a problem with how the doc was created? One was just a simple text file created on MS Excel on my mac.

`Error: Unexpected xml node in parseOpen:
{
    "name": "coreProperties",
    "attributes": {
        "xmlns": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
        "xmlns:cp": "http://schemas.openxmlformats.org/package/2006/metadata/core-properties",
        "xmlns:dc": "http://purl.org/dc/elements/1.1/",
        "xmlns:dcterms": "http://purl.org/dc/terms/",
        "xmlns:xsi": "http://www.w3.org/2001/XMLSchema-instance"
    },
    "isSelfClosing": false
}

at utils.inherits.parseOpen (/var/task/node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:107:17)
at SAXStream.<anonymous> (/var/task/node_modules/exceljs/lib/xlsx/xform/base-xform.js:65:14)
at emitOne (events.js:77:13)
at SAXStream.emit (events.js:169:7)
at Object.me._parser.(anonymous function) [as onopentag] (/var/task/node_modules/sax/lib/sax.js:245:15)
at emit (/var/task/node_modules/sax/lib/sax.js:615:33)
at emitNode (/var/task/node_modules/sax/lib/sax.js:620:3)
at openTag (/var/task/node_modules/sax/lib/sax.js:801:3)
at Object.write (/var/task/node_modules/sax/lib/sax.js:1261:31)
at SAXStream.write (/var/task/node_modules/sax/lib/sax.js:227:16)
at Entry.ondata (_stream_readable.js:528:20)
at emitOne (events.js:77:13)
at Entry.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:146:16)
at Entry.Readable.push (_stream_readable.js:110:10)
at Entry.Transform.push (_stream_transform.js:127:32)`

**Comment by Siemienik** [comment]
probably it's `xls` file instead of `xlsx` #148
