### ISSUE TITLE
[BUG] Formulae in "Formatting Rules" throws exception

### ISSUE THREAD

**Issue by jonathankeebler** [exceljs/exceljs#2311]
## 🐛 Bug Report

If a formatting rule is setup for a sheet, that references another sheet, an exception is thrown when you call `XLSX.writeBuffer`
<img width="767" alt="Screenshot 2023-07-19 at 2 51 12 PM" src="https://github.com/exceljs/exceljs/assets/4992815/ff032453-cf0e-4e9f-b353-af6724968664">

Cell `model` looks like this:
`````
{
  type: 'expression',
  x14Id: '{BB2F621F-E459-4F3E-9A72-51C5F7F3EB5F}',
  priority: 42,
  ref: 'C16'
}
`````

Exception:
````
TypeError: Cannot read properties of undefined (reading 'forEach')
    at CfRuleXform.renderCellIs (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:175:20)
    at CfRuleXform.render (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:125:14)
    at /Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:29:25
    at Array.forEach (<anonymous>)
    at ConditionalFormattingXform.render (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:26:17)
    at /Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:41:20
    at Array.forEach (<anonymous>)
    at ConditionalFormattingsXform.render (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:40:11)
    at WorkSheetXform.render (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xform/sheet/worksheet-xform.js:329:36)
    at /Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xlsx.js:562:22
    at Array.forEach (<anonymous>)
    at XLSX.addWorksheets (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xlsx.js:560:22)
    at XLSX.write (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xlsx.js:654:16)
    at async XLSX.writeBuffer (/Users/jonathan/baseline/service-2.0/node_modules/exceljs/lib/xlsx/xlsx.js:684:5)
`````

Lib version: 4.3.0

## Steps To Reproduce
[sample.xlsx](https://github.com/exceljs/exceljs/files/12099166/sample.xlsx)

```javascript
const workbook = new Excel.Workbook();
await workbook.xlsx.load(file);
await workbook.xlsx.writeBuffer();
```

## The expected behaviour:

The conditional formatting is applied.

## Possible solution (optional, but very helpful):

In `/lib/xlsx/xform/sheet/cf/cf-rule-xform.js`, this code could be patched to not assume formulae is set:
```javascript
renderExpression(xmlStream, model) {
    xmlStream.openNode(this.tag, {
      type: 'expression',
      dxfId: model.dxfId,
      priority: model.priority,
    });

    this.formulaXform.render(xmlStream, model.formulae[0]);

    xmlStream.closeNode();
  }

```

**Comment by MarcosParengo** [comment]
This is solved?

**Comment by Jervis-Miao** [comment]
Has the problem been solved？

**Comment by mashpie** [comment]
bug seams to persist:

```
[...]/monorepo/node_modules/.pnpm/exceljs@4.4.0/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:158
    this.formulaXform.render(xmlStream, model.formulae[0]);
                                                      ^
TypeError: Cannot read properties of undefined (reading '0')
```

**Comment by AndresDSoto** [comment]
In the above pr I have a very simple fix if you want to point to that branch in your package.json. You can install it using this command.
`npm i https://github.com/AndresDSoto/exceljs/tarball/bug-fix/2311-x14Id-expressions`

**Comment by mashpie** [comment]
Thank you! For now I apply a similar patch with `pnpm patch`:

```diff
diff --git a/lib/xlsx/xform/sheet/cf/cf-rule-xform.js b/lib/xlsx/xform/sheet/cf/cf-rule-xform.js
index 22b3e44ecc8731a3a04bac22d43f32c4211dfbe3..95208161a56e98b6ba49ba9dee8524c8051c1d0a 100644
--- a/lib/xlsx/xform/sheet/cf/cf-rule-xform.js
+++ b/lib/xlsx/xform/sheet/cf/cf-rule-xform.js
@@ -155,7 +155,7 @@ class CfRuleXform extends CompositeXform {
       priority: model.priority,
     });
 
-    this.formulaXform.render(xmlStream, model.formulae[0]);
+    this.formulaXform.render(xmlStream, model.formulae?.[0]);
 
     xmlStream.closeNode();
   }
```

**Comment by ericLemanissier** [comment]
@Siemienik can this issue be reopenned ? I have the same problem:
```

153 |       type: 'expression',
154 |       dxfId: model.dxfId,
155 |       priority: model.priority,
156 |     });
157 | 
158 |     this.formulaXform.render(xmlStream, model.formulae[0]);
                                                    ^
TypeError: undefined is not an object (evaluating 'model.formulae[0]')
      at renderExpression (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:158:47)
      at render (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/cf-rule-xform.js:122:14)
      at <anonymous> (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:29:25)
      at forEach (1:11)
      at render (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formatting-xform.js:26:17)
      at <anonymous> (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:41:20)
      at forEach (1:11)
      at render (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/cf/conditional-formattings-xform.js:40:11)
      at render (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xform/sheet/worksheet-xform.js:330:36)
      at <anonymous> (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xlsx.js:564:22)
      at forEach (1:11)
      at <anonymous> (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xlsx.js:562:22)
      at addWorksheets (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xlsx.js:554:23)
      at <anonymous> (/tmp/windmill/wk-default-713e0b1ce123-6HCPC/0199e6b1-1c33-3b5d-a077-a828b9d9ec18/node_modules/exceljs/lib/xlsx/xlsx.js:655:16)
```
