### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'anchors')

### ISSUE THREAD

**Issue by markusjohnsson** [exceljs/exceljs#2591]
## 🐛 Bug Report

Lib version: 4.4.0

I have a file which crashes the loader. I have reduced it to just a single chart with some graphics, but I still need to check if I can share it. I'll update this issue with the file when I've cleared this. This is the error:

```
        (drawing.anchors || []).forEach(anchor => {
                 ^

TypeError: Cannot read properties of undefined (reading 'anchors')
    at /xyz/node_modules/exceljs/lib/xlsx/xlsx.js:100:18
    at Array.forEach (<anonymous>)
    at XLSX.reconcile (/xyz/node_modules/exceljs/lib/xlsx/xlsx.js:92:33)
    at XLSX.load (/xyz/node_modules/exceljs/lib/xlsx/xlsx.js:411:10)
    at async XLSX.readFile (/xyz/node_modules/exceljs/lib/xlsx/xlsx.js:55:24)
```

<img width="532" alt="image" src="https://github.com/exceljs/exceljs/assets/557685/d9588840-b7aa-4f29-9ce4-dfee34d2b9d0">

## Steps To Reproduce

```javascript
const ExcelJS = require('exceljs');
const wb = new ExcelJS.Workbook();
wb.xlsx.readFile('test2.xlsx').then(() => {
    console.log("File is loaded");
});

```

## The expected behaviour:

The file would load (as it does in Excel) without crashing. I have no need to load any charts, I'm only interested in data cells. I also have no need of saving the file back.

## Possible solution (optional, but very helpful):

With this change the file loads with exceljs:

in xlsx.js, in class XLSL, method 'reconcile':

```diff
    Object.keys(model.drawings).forEach(name => {
      const drawing = model.drawings[name];
      const drawingRel = model.drawingRels[name];
-      if (drawingRel) {
+      if (drawing && drawingRel) {
        drawingOptions.rels = drawingRel.reduce((o, rel) => {
          o[rel.Id] = rel;
          return o;
        }, {});
        (drawing.anchors || []).forEach(anchor => {
          const hyperlinks = anchor.picture && anchor.picture.hyperlinks;
          if (hyperlinks && drawingOptions.rels[hyperlinks.rId]) {
            hyperlinks.hyperlink = drawingOptions.rels[hyperlinks.rId].Target;
            delete hyperlinks.rId;
          }
        });
        drawingXform.reconcile(drawing, drawingOptions);
      }
```

**Comment by DarkTraveler** [comment]
I faced the same problem. I had to change another worksheet-xform.js file.

```
          drawing.anchors.forEach(anchor => {
            if (anchor.medium) {
```

Added check

```
        if(drawing)
        {
          drawing.anchors.forEach(anchor => {
```

**Comment by ariel-equall** [comment]
Hitting this same issue - any chance it'll be prioritized?

**Comment by EOlivoni** [comment]
Had the same issue, please accept solutions mr excel.js creator.

**Comment by ucozlab** [comment]
+1 here. same parsing error
