### ISSUE TITLE
请求帮助，传统项目直接在浏览器里引用这个为什么报错

### ISSUE THREAD

**Issue by zhaoyan519** [exceljs/exceljs#2724]
引用了这个 https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.js ， 报错如下，请求帮助

TypeError: fs.createWriteStream is not a function
    at XLSX.writeFile (excel.min.js:16156:59)
    at wn.showCacheInfo (manager.js:100:22)
    at He (vue.min.2.6.12.js:6:11384)
    at a.n (vue.min.2.6.12.js:6:13168)
    at He (vue.min.2.6.12.js:6:11384)
    at e.$emit (vue.min.2.6.12.js:6:34373)
    at a.handleClick (index.js:1:125669)
    at He (vue.min.2.6.12.js:6:11384)
    at HTMLButtonElement.n (vue.min.2.6.12.js:6:13168)

**Comment by LSL1618** [comment]
用这个 **[https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js](https://cdn.jsdelivr.net/npm/exceljs@4.4.0/dist/exceljs.min.js)**
我一般都是下载到项目内部来使用
`<script type="text/javascript" src="../static/plugins/exceljs/4.4.0/exceljs.min.js"></script>`

**Comment by zonefile** [comment]
@LSL1618 可以试试南科大的公共 CDN: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/exceljs/4.4.0/exceljs.min.js

或者 Zstatic 的也不错: https://s4.zstatic.net/ajax/libs/exceljs/4.4.0/exceljs.min.js

**Comment by LSL1618** [comment]
> @LSL1618 可以试试南科大的公共 CDN: https://mirrors.sustech.edu.cn/cdnjs/ajax/libs/exceljs/4.4.0/exceljs.min.js
> 
> 或者 Zstatic 的也不错: https://s4.zstatic.net/ajax/libs/exceljs/4.4.0/exceljs.min.js

确实不错，可我的是内网项目，无法访问外网，所以静态资源必须放在项目内部。

**Comment by AlwaysNoobCoder** [comment]
浏览器里面哪里来的`fs`，那是nodejs里才有的吧

**Comment by LSL1618** [comment]
> 浏览器里面哪里来的`fs`，那是nodejs里才有的吧

fs确实是nodejs才有的，题主引用错了文件，exceljs.js是nodejs端用的，exceljs.min.js才是浏览器端用的。
