### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'comments')

### ISSUE THREAD

**Issue by PavelDAS** [exceljs/exceljs#2797]
Server running at http://localhost:3000
Произошла ошибка: TypeError: Cannot read properties of undefined (reading 'comments')
    at c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js:465:60
    at Array.reduce (<anonymous>)
    at WorkSheetXform.reconcile (c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js:459:46)
    at c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xlsx.js:137:22
    at Array.forEach (<anonymous>)
    at XLSX.reconcile (c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xlsx.js:135:22)
    at XLSX.load (c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xlsx.js:416:10)
    at async XLSX.readFile (c:\xampp\htdocs\ex\node_modules\exceljs\lib\xlsx\xlsx.js:58:24)
    at async Object.parse (c:\xampp\htdocs\ex\src\services\excelService.js:20:5)
    at async parseExcel (c:\xampp\htdocs\ex\src\controllers\excelController.js:9:22)

  "name": "@wmakeev/exceljs",
  "version": "4.4.5",

**Comment by ChandanChainani** [comment]
@PavelDAS Please can you share the example so it is easier to regenerate the issue

**Comment by Mercer-L** [comment]
@PavelDAS Have you fixed that problem？I had the same problem with my exceljs version "^4.4.0"。Here is my code：
`let excel_path = args.excel_path;
 let sheet_name = args.sheet_value;
 const workbook = new Workbook();
 await workbook.xlsx.readFile(excel_path);` 
only a few excel files will trigger this error，others will not. 
If you fixed that, please give me some advise, thx :)

**Comment by PavelDAS** [comment]
node_modules\exceljs\lib\xlsx\xform\sheet\worksheet-xform.js
~465

`      if (rel.Type === RelType.VmlDrawing && model.comments && model.comments.length) {
        const vmlComment = options.vmlDrawings[rel.Target].comments;
        model.comments.forEach((comment, index) => {
          comment.note = Object.assign({}, comment.note, vmlComment[index]);
        });
      }
`
      
      add if:
      
`
      if (rel.Type === RelType.VmlDrawing && model.comments && model.comments.length) {
		if (typeof options.vmlDrawings[rel.Target] !== 'undefined') {
			const vmlComment = options.vmlDrawings[rel.Target].comments;
			
			model.comments.forEach((comment, index) => {
          comment.note = Object.assign({}, comment.note, vmlComment[index]);
        });
		}

      }
`

**Comment by Mercer-L** [comment]
thx, my friend. i'll have a try.   :)

**Comment by suhli** [comment]
any update here?

**Comment by MichaelPote** [comment]
This bug is because Excel itself names comment `parts xl/comments1.xml` and that is the only shape ExcelJS parses. Other generators (like openpyxl, WPS Office, Google exports) use paths like `xl/comments/comment1.xml`, so the worksheet's relationship points at a part ExcelJS never loaded, and its reconcile step then dereferences undefined. 

The only choice until the devs fix this is to manually scrub all comments out of the XLSX zip file before loading it :/
