### ISSUE TITLE
[BUG] After upgrade to 4.4 some excel 2003 file get `invalid signature: 0xe011cfd0` error.

### ISSUE THREAD

**Issue by toknT** [exceljs/exceljs#2798]
## 🐛 Bug Report

Lib version: 4.4.0

## Steps To Reproduce

Yeah it's 2024 but some of my file is created by excel 2003 ...lol

```javascript
const ExcelJS = require("exceljs");
const main = async () => {
  const workbookReader = new ExcelJS.stream.xlsx.WorkbookReader(
    "./unable_read_20240719.xls"
  );
  try {
    for await (const worksheetReader of workbookReader) {
      for await (const row of worksheetReader) {
        console.debug("I am ok");
      }
    }
  } catch (error) {
    console.error("error:", error);
  }
};
main();
```

```sh
node .\index.js                                                                                                                           417ms  18:22 (Fri) 
error: Error: invalid signature: 0xe011cfd0
    at C:\workspace\exceljs_testing\node_modules\unzipper\lib\parse.js:70:26
    at tryCatcher (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\workspace\exceljs_testing\node_modules\bluebird\js\release\async.js:17:14)
    at process.processImmediate (node:internal/timers:478:21)
```
[unable_read_20240719.xls](https://github.com/user-attachments/files/16310739/unable_read_20240719.xls)

**Comment by toknT** [comment]
sorry in old version we have converting xls to xlsx , no the problem of this library
