### ISSUE TITLE
Crash when reading file with picture and shape

### ISSUE THREAD

**Issue by muscapades** [exceljs/exceljs#324]
Since version 4.8, we have a problem reading excel files that contains both shapes and pictures. Last good version was 4.6.

Simplest case I can find is that two of these files (that contain either a rectangle or a picture) are read fine, but the last one containing both a picture and a rectangle gives the following stack trace (with version 0.4.10):
`
2017-05-24T11:06:44.284Z - error:  TypeError: Cannot read property 'rId' of null
    at reconcile (C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xform\drawing\two-cell-anchor-xform.js:111:41)
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xform\drawing\drawing-xform.js:99:38
    at Array.forEach (native)
    at reconcile (C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xform\drawing\drawing-xform.js:98:19)
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:99:22
    at Array.forEach (native)
    at Object.reconcile (C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:92:33)
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:316:14
`
[picture-alone.xlsx](https://github.com/guyonroche/exceljs/files/1025316/picture-alone.xlsx)
[picture-and-shape.xlsx](https://github.com/guyonroche/exceljs/files/1025315/picture-and-shape.xlsx)
[shape-alone.xlsx](https://github.com/guyonroche/exceljs/files/1025314/shape-alone.xlsx)

I have reproduced with other shapes and pictures too.

The error is thrown when I call XLSX.Workbook().xlsx.readFile(filePath).

I have also tried safeguarding the code in two-cell-anchor-xform.js:111 against !model.picture - I then see a similar problem in another location:
`
2017-05-24T11:10:50.762Z - error:  TypeError: Cannot read property 'index' of undefined
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:287:35
    at Array.forEach (native)
    at reconcile (C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:284:25)
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:113:22
    at Array.forEach (native)
    at Object.reconcile (C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:111:22)
    at C:\Users\morten\bts\git\BATools\service\node_modules\exceljs\dist\es5\xlsx\xlsx.js:316:14
`

If I safeguard !anchor.medium there, it works.

**Comment by papandreou** [comment]
This was fixed in 0.6.0 (dfd12e80f24d922a20007243619e2f4850dcaa13)
