### ISSUE TITLE
TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by abdsam1** [exceljs/exceljs#325]
```javascript
var path = require('path');
var cellread2 = function () {
  var Excel;
  var filePath = path.resolve('E:/', 'excel.xlsx');
  if (typeof require !== 'undefined') {
    Excel = require('exceljs');
  }
  var wb = new Excel.Workbook();
  wb.xlsx.readFile(filePath).then(function (data) {
    var worksheet = wb.getWorksheet('Sheet1');
    var cellValue = worksheet.getRow(1).getCell(1).value;
    console.log('cellValue', cellValue);
  }).catch(function (e) {
    console.log(e);
  });
}
cellread2();
```

I am using the above code to read a xlsx file from the same directory as my js file. And I am getting the following error: 
```
TypeError: Cannot read property 'index' of undefined
 atC:\Users\AbdulSamad\AppData\Roaming\npm\node_modules\exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:287:35 
at Array.forEach (native)
at reconcile (C:\Users\AbdulSamad\AppData\Roaming\npm\node_modules\exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:284:25)
at C:\Users\Abdul Samad\AppData\Roaming\npm\node_modules\exceljs\dist\es5\xlsx\xlsx.js:113:22
at Array.forEach (native)
at Object.reconcile (C:\Users\Abdul Samad\AppData\Roaming\npm\node_modules\exceljs\dist\es5\xlsx\xlsx.js:111:22)
at C:\Users\Abdul Samad\AppData\Roaming\npm\node_modules\exceljs\dist\es5\xlsx\xlsx.js:316:14
```
I fixed this problem by making the following changes in "exceljs\dist\es5\xlsx\xform\sheet\worksheet-xform.js:284:25" if I enclosed the _forEach_ loop at line 284 into an _if_ statement: 
```javascript
if (drawing.anchors && drawing.anchors.length > 0) {
            drawing.anchors.forEach(function (anchor) {              
              if (anchor.medium && anchor.range) {
                console.log('andchor', anchor);
                var image = {
                  type: 'image',
                  imageId: anchor.medium.index,
                  range: anchor.range
                };
                model.media.push(image);
              }
            });
          }
```

**Comment by vasiliyb** [comment]
Same Issue,

```
function createNewExcelData() {
            let workbook = new exceljs.Workbook();
            return workbook.xlsx.readFile(ingestionConfig.outputFileName).then(function() {
                let worksheet = workbook.getWorksheet(1);

               worksheet.getRow(1).values = ['column1Name', 'column2Name'];
                workbook.commit();
                return workbook;
            });
        }
```

**Comment by kotmatpockuh** [comment]
Also, have the same issue. Quite easy to fix. Not sure why the owner doesn't fix it :(

**Comment by Siemienik** [comment]
Could anyone of You write pull request and become to be a contributor :)?
