### ISSUE TITLE
Error when reading from XLSX file in nodejs

### ISSUE THREAD

**Issue by Vishal1419** [exceljs/exceljs#415]
Here is the error when I am trying to read from a file called GSTR1.xlsx

Uncaught (in promise) Error: Unexpected xml node in parseOpen: {"name":"cp:version","attributes":{},"isSelfClosing":false}
    at module.exports.parseOpen (C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xform\core\core-xform.js:85:15)
    at SAXStream.<anonymous> (C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xform\base-xform.js:61:14)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:188:7)
    at SAXParser.me._parser.(anonymous function) [as onopentag] (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:258:17)
    at emit (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:629:5)
    at openTag (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:825:5)
    at SAXParser.write (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:1278:15)
    at SAXStream.write (C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:239:18)
parseOpen @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xform\core\core-xform.js:85
(anonymous) @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xform\base-xform.js:61
emitOne @ events.js:96
emit @ events.js:188
me._parser.(anonymous function) @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:258
emit @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:624
emitNode @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:629
openTag @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:825
write @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:1278
SAXStream.write @ C:\Users\Vishal\Desktop\one-file\node_modules\sax\lib\sax.js:239
(anonymous) @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:196
Promish @ C:\Users\Vishal\Desktop\one-file\node_modules\promish\lib\promish-class.js:23
write @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:195
_pipe @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:201
_flush @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:265
writeComplete @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:280
end @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:290
pipe @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\stream-buf.js:340
parseStream @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xform\base-xform.js:82
(anonymous) @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\xlsx\xlsx.js:299
emitOne @ events.js:96
emit @ events.js:188
(anonymous) @ C:\Users\Vishal\Desktop\one-file\node_modules\exceljs\dist\es5\utils\zip-stream.js:67

Nodejs gives me another error:
Unclosed root tag
[GSTR1.xlsx](https://github.com/guyonroche/exceljs/files/1331071/GSTR1.xlsx)

**Comment by shareefsakk** [comment]
I am also getting this "Unclosed root tag" error If the excel is created by Microsoft offices but works well when It is created by LibreOffice.
