### ISSUE TITLE
Version 0.5.1 not working on node 4

### ISSUE THREAD

**Issue by Nitesh7** [exceljs/exceljs#542]
Version 0.5.1 in dependencies has  "promish": ">=5.0.2". As promish was deployed to npm yesterday with 5.0.2 version now our build is no longer working. Following error while starting app

/Users/nitesh.malhotra/workspace/paytm-seats/node_modules/exceljs/node_modules/promish/lib/promish-class.js:12
  class Promish extends Base {
  ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/nitesh.malhotra/workspace/paytm-seats/node_modules/exceljs/node_modules/promish/lib/promish.js:4:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by antonshokut** [comment]
I have the same issue. 
@guyonroche could you fix it please?

**Comment by TimTilroy** [comment]
Same issue here on Node 4.5.

**Comment by jloveridge** [comment]
Node 4.x LTS is EOL from a maintenance stand point at the end of the month. Probably best that you try to upgrade your environments.

**Comment by sudhashree93** [comment]
Facing the same issue. Is there any way to fix this ?

**Comment by guyonroche** [comment]
I agree - the dist build is a bit of a mess. I will try to take some time to look into it...

In the mean time, the following workaround should at least allow the node v4 apps to run...
```
node --strict_mode app.js
```

**Comment by guyonroche** [comment]
Dropped non-native Promise implementations as of v3.0.0
