### ISSUE TITLE
this.diagonal.style throws exception

### ISSUE THREAD

**Issue by cubbuk** [exceljs/exceljs#59]
Hi,

While reading a xlsx file I am getting the following error at exceljs/lib/xlsx/border.js:159:34:

if (this.diagonal.style) {
                                 ^

TypeError: Cannot read property 'style' of undefined
node_modules/exceljs/lib/xlsx/border.js:159:34)

seems like diagonal object is undefined, and in get xml() method if I instantiate diagonal object I can read the file. I don't know the details but this seems to work, if it seems ok could it be updated in the main code base.

Thanks.

get xml() {
        // return string containing the <border> definition
        if (this._xml === undefined) {
            if (this.left) {
                this.diagonal = this.diagonal || {}; // if diagonal does not exist, create it.
                var xml = ['<border'];
                // left, right, top bottom
                if (this.diagonal.style) {
                    if (this.diagonal.up) {
                        xml.push(' diagonalUp="1"');
                    }
                    if (this.diagonal.down) {
                        xml.push(' diagonalDown="1"');
                    }
                }
                xml.push('>');
                xml.push(this.left.xml);
                xml.push(this.right.xml);
                xml.push(this.top.xml);
                xml.push(this.bottom.xml);
                xml.push(this.diagonal.xml);
                xml.push('</border>');
                this._xml = xml.join('');
            } else {
                // special case - empty border
                this._xml = '<border><left/><right/><top/><bottom/><diagonal/></border>';
            }
        }
        return this._xml;
    },

**Comment by dmajoraddnine** [comment]
I also ran into this error in version 0.2.4, but upgrading to version 0.2.6 seems to have fixed it!

**Comment by desecheo** [comment]
I'm getting the same error with 0.2.6.

**Comment by chamnap** [comment]
version 0.2.6 doesn't fix for me!

**Comment by baderahmed** [comment]
Same problem 

version 0.2.8 

if (this.diagonal.style) {
                         ^

TypeError: Cannot read property 'style' of undefined
    at Object.xml (/node_modules/exceljs/lib/xlsx/border.js:158:26)
    at utils.inherits._addBorder (/node_modules/exceljs/lib/xlsx/stylemanager.js:381:43)
    at SAXStream.<anonymous> (/node_modules/exceljs/lib/xlsx/stylemanager.js:204:20)
    at emitOne (events.js:90:13)
    at SAXStream.emit (events.js:182:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (l/node_modules/sax/lib/sax.js:245:15)
    at emit (/node_modules/sax/lib/sax.js:615:33)
    at emitNode (/node_modules/sax/lib/sax.js:620:3)
    at closeTag (/node_modules/sax/lib/sax.js:861:5)
    at Object.write (/node_modules/sax/lib/sax.js:1294:29)
    at SAXStream.write (/node_modules/sax/lib/sax.js:227:16)
    at Entry.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at Entry.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Entry.Readable.push (_stream_readable.js:111:10)
    at Entry.Transform.push (_stream_transform.js:128:32)
    at afterTransform (_stream_transform.js:77:12)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Entry.PassThrough._transform (_stream_passthrough.js:21:3)
    at Entry.Transform._read (_stream_transform.js:167:10)
    at Entry.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Entry.Writable.write (_stream_writable.js:215:11)
    at InflateRaw.ondata (_stream_readable.js:536:20)
    at emitOne (events.js:90:13)
    at InflateRaw.emit (events.js:182:7)

**Comment by chamnap** [comment]
I did this, and it solves the problem. I go to Microsoft Excel and save as a new file. `exceljs` parses the new one nicely.

**Comment by guyonroche** [comment]
@cubbuk @dmajoraddnine @baderahmed @chamnap 
I have completely refactored the xlsx rendering code and I'm now working through the issues. Could you confirm whether this is still a problem?
Thanks

**Comment by chamnap** [comment]
I think yes. One or two months ago, I already tried out the latest and master branch, and it failed.

**Comment by Siemienik** [comment]
https://github.com/exceljs/exceljs/blob/master/lib/xlsx/xform/style/border-xform.js#L119
