### ISSUE TITLE
Unhandled Promise rejection: Cannot read property 'then' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by akmalul** [exceljs/exceljs#615]
I try to use 

`res.attachment(monthNames[parseInt(month)-1]+".xlsx");
        workbook.xlsx.write(res).then(function() {
            res.end();
        })`

The code working well in the local, but when I upload it into Ms. Azure, I got the following error.

`Unhandled Promise rejection: Cannot read property 'then' of null ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'then' of null
    at Promish (D:\home\site\wwwroot\node_modules\promish\lib\promish-class.js:16:46)
    at Promish.ZoneAwarePromise.then (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:616:32)
    at module.exports.write (D:\home\site\wwwroot\node_modules\exceljs\dist\es5\xlsx\xlsx.js:598:41)
    at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)
    at ZoneDelegate.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:242:26)
    at Zone.run (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:113:43)
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:535:57
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
    at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
    at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5) TypeError: Cannot read property 'then' of null
    at Promish (D:\home\site\wwwroot\node_modules\promish\lib\promish-class.js:16:46)
    at Promish.ZoneAwarePromise.then (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:616:32)
    at module.exports.write (D:\home\site\wwwroot\node_modules\exceljs\dist\es5\xlsx\xlsx.js:598:41)
    at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)
    at ZoneDelegate.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:242:26)
    at Zone.run (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:113:43)
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:535:57
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
    at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
    at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
{ Error: Uncaught (in promise): TypeError: Cannot read property 'then' of null
TypeError: Cannot read property 'then' of null
    at Promish (D:\home\site\wwwroot\node_modules\promish\lib\promish-class.js:16:46)
    at Promish.ZoneAwarePromise.then (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:616:32)
    at module.exports.write (D:\home\site\wwwroot\node_modules\exceljs\dist\es5\xlsx\xlsx.js:598:41)
    at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)
    at ZoneDelegate.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:242:26)
    at Zone.run (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:113:43)
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:535:57
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
    at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
    at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:811:33)
    at AppInsightsAsyncCorrelatedErrorWrapper (D:\home\site\wwwroot\node_modules\applicationinsights\out\AutoCollection\CorrelationContextManager.js:172:18)
    at resolvePromise (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:501:31)
    at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:538:17
    at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
    at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
    at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
    at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
    at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  rejection: 
   TypeError: Cannot read property 'then' of null
       at Promish (D:\home\site\wwwroot\node_modules\promish\lib\promish-class.js:16:46)
       at Promish.ZoneAwarePromise.then (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:616:32)
       at module.exports.write (D:\home\site\wwwroot\node_modules\exceljs\dist\es5\xlsx\xlsx.js:598:41)
       at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)
       at ZoneDelegate.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:242:26)
       at Zone.run (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:113:43)
       at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:535:57
       at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
       at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
       at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
       at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
       at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5),
  promise: 
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value: 
      TypeError: Cannot read property 'then' of null
          at Promish (D:\home\site\wwwroot\node_modules\promish\lib\promish-class.js:16:46)
          at Promish.ZoneAwarePromise.then (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:616:32)
          at module.exports.write (D:\home\site\wwwroot\node_modules\exceljs\dist\es5\xlsx\xlsx.js:598:41)
          at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)
          at ZoneDelegate.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:242:26)
          at Zone.run (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:113:43)
          at D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:535:57
          at ZoneDelegate.invokeTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:275:35)
          at Zone.runTask (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:151:47)
          at drainMicroTaskQueue (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:433:35)
          at Immediate.ZoneTask.invoke (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:349:25)
          at Immediate.data.args.(anonymous function) (D:\home\site\wwwroot\node_modules\zone.js\dist\zone-node.js:1359:25)
          at runCallback (timers.js:672:20)
          at tryOnImmediate (timers.js:645:5)
          at processImmediate [as _immediateCallback] (timers.js:617:5) },
  zone: 
   Zone {
     _properties: {},
     _parent: null,
     _name: '<root>',
     _zoneDelegate: 
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: null,
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: null,
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: null,
        _invokeZS: null,
        _invokeDlgt: null,
        _invokeCurrZone: null,
        _handleErrorZS: null,
        _handleErrorDlgt: null,
        _handleErrorCurrZone: null,
        _scheduleTaskZS: null,
        _scheduleTaskDlgt: null,
        _scheduleTaskCurrZone: null,
        _invokeTaskZS: null,
        _invokeTaskDlgt: null,
        _invokeTaskCurrZone: null,
        _cancelTaskZS: null,
        _cancelTaskDlgt: null,
        _cancelTaskCurrZone: null,
        _hasTaskZS: null,
        _hasTaskDlgt: null,
        _hasTaskCurrZone: null } },
  task: 
   ZoneTask {
     runCount: 1,
     type: 'microTask',
     zone: 
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }`

 `at Promise.all.then (D:\home\site\wwwroot\application\controllers\shift_schedule.js:670:23)` is pointed `to workbook.xlsx.write(res).then(function() {`

I used Node.js version 8.1.3
Any help in this regard? 
Thanks in advance

**Comment by maxgodi** [comment]
Same error here. Need help

**Comment by alubbe** [comment]
can you please a complete example that we can run? that would really help with debugging

**Comment by nimatullah** [comment]
@alubbe , one more thing. It works find on ubuntu server. When I dockerize my application I recieve this error. I have created gist for all my docker and docker-compose files. pleaset look at https://gist.github.com/nimatullah/3f4927ccb973ba1fd292d56c33fca81e

**Comment by matiullah-netlinks** [comment]
@alubbe I have the same issue, and still waiting for your answer

**Comment by Siemienik** [comment]
are you trying use `await xlsx.writeFile()`?

**Comment by matiullah-netlinks** [comment]
@Siemienik `workbook.xlsx
    .writeFile(xlPath)
    .then(() => {
        sendJsonResponse(res, 200, "ok");
    })
    .catch(error => {
        sendJsonResponse(res, 500, error);
    });`

**Comment by Siemienik** [comment]
@matiullah-netlinks 
```js
const fileStream = fs.createWriteStream(xlPath);
fileStream .on('finish', () => { sendJsonResponse(res, 200, "ok"); });
fileStream .on('error', error => { sendJsonResponse(res, 500, error); });
wb.xlsx.write(fileStream);
```
could You check this one?

**Comment by alubbe** [comment]
@matiullah-netlinks did you try running what @Siemienik proposed?

**Comment by nimatullah** [comment]
@alubbe , It worked. Thanks

**Comment by matiullah-netlinks** [comment]
@alubbe , @Siemienik, worked thanks

**Comment by alubbe** [comment]
Awesome!
