### ISSUE TITLE
Excel file not opening on every plateform with Node

### ISSUE THREAD

**Issue by Gildewarz777** [exceljs/exceljs#739]
Hello, I am currently struggling with opening the file generated by exceljs (v1.7.0) on MS Excel. I can open it but Excel (v16.21.1) says that some styling were not imported and no styling is taken into account. 
<img width="433" alt="capture d ecran 2019-02-05 a 14 34 12" src="https://user-images.githubusercontent.com/10724721/52276725-39c8dc00-2953-11e9-9d40-2f7ad5830c3e.png">
[EN Traduction] - "Sorry... We found a problem in the file, but we can try to recover as much content as we can. If you trust were the file came from, click yes"

That gives me this Excel that doesn't take all my styling: 
<img width="1414" alt="capture d ecran 2019-02-05 a 14 47 38" src="https://user-images.githubusercontent.com/10724721/52277467-11da7800-2955-11e9-85a5-51948148ecdd.png">

If I try to open the file in the browser with the extension `Office Editing for Docs, Sheets & Slides` it shows me this error:
![screenshot 2019-02-05 at 14 29 58](https://user-images.githubusercontent.com/10724721/52276521-be672a80-2952-11e9-9f15-b7fa33a14873.png)

BUT if I manually create a Google spreadsheet and import from there my generated file, the file is correctly displayed and opens correctly: 
![screenshot 2019-02-05 at 14 40 57](https://user-images.githubusercontent.com/10724721/52277099-24a07d00-2954-11e9-937b-dd8c0e942f8d.png)

And kind of weird, but I generate the file, opens it on Google spreadsheet, download it from there on xlsx format and opens this downloaded file, the file opens correctly. So Google must be doing something I am not. As most of my users will be using Excel, it's kind of annoying to push them to use Spreadsheet.

Here is the code that I use to  generate and style my file
```js
  const workbook = new Excel.Workbook()

  // Worksheet
  const worksheet = workbook.addWorksheet('Detailed capitalization table', {
    pageSetup: { paperSize: 9, orientation: 'landscape', },
  })

  worksheet.views = [
    { state: 'frozen', ySplit: 4, topLeftCell: 'A3', },
    {
      showGridLines: false,
    },
  ]

  // Construction of columns
  // Construction of frozen upper part
  // Put data into columns
```

And later I do 
```js
workbook.xlsx.writeFile('path/to/file.xlsx') // With path to file
```

I tried without any styling but even then it doesn't work. Still errors when i try to open the file.
Thanks for reading, if you have any lead that would be super helpful!

**Comment by nick-keller** [comment]
We actually have the same issue, I cannot get rid of the warning message when opening generated files with MS Excel but opening it in Google drive work fine.
I also lose some styling in Excel.

**Comment by Siemienik** [comment]
honestly in some files I have same issue, I didn't point  source of this error ;( If You have any idea what is the reason I will be really thankful ;)

**Comment by IgnatovDan** [comment]
This message can be caused by an incorrect order of some nodes in internal styles.xml/sheet1.xml/... files, or by an incomplete set of values, or by an incorrect (non xml) content in these files... To investigate such issues, I tried to create as simple content as possible and to save it. Then, I created the same content manually in Excel, saved it and compared the resulting files.

In your code, the [state: 'frozen'](https://codepen.io/DanIgnatov/pen/OdYRWV?editors=1010) option seems to be the source of that error message. It seems that you want to initialize the '18.3.1.66 pane (View Pane)' object (see [Office Open XML File Formats](https://www.ecma-international.org/publications/standards/Ecma-376.htm) for more details) that is represented by the [Frozen View](https://github.com/exceljs/exceljs#frozen-views) ExcelJS entity.

Adjust it in MS Excel manually, save changes into XLSX file and compare it with the generated ExcelJS file. 

Don't hezitate to adjust another approach to investigate this issue if I mistunderstood the initial scenario or ExcelJS implementation details.

**Comment by Gildewarz777** [comment]
Hi, 
I've created a worksheet with **nothing** on it, but I still get the errors. 
Here is the code : 
```js
  const workbook = await new Excel.Workbook()
  const worksheet = await workbook.addWorksheet('Worksheet')
  workbook.xlsx.writeFile('path/to/file.xlsx') // With path to file
}
```

Here is the xml that results from the generated xlsx file:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/xl/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/>
  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>
```

And here is the xml when I import the xlsx on Google Spreadsheet and download it in xlsx from there: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default ContentType="application/xml" Extension="xml"/>
  <Default ContentType="application/vnd.openxmlformats-package.relationships+xml" Extension="rels"/>
  <Override ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml" PartName="/xl/worksheets/sheet1.xml"/>
  <Override ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml" PartName="/xl/sharedStrings.xml"/>
  <Override ContentType="application/vnd.openxmlformats-officedocument.drawing+xml" PartName="/xl/drawings/drawing1.xml"/>
  <Override ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml" PartName="/xl/styles.xml"/>
  <Override ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml" PartName="/xl/workbook.xml"/>
</Types>
```

The error is definitely in this, as I can open the xlsx generated from Google Spreadsheet no problem. If you have any idea of how I can make this work, thousand thanks. I just really want this to work.

**Comment by IgnatovDan** [comment]
I have checked how [ExcelJS exports empty xlsx file](https://codepen.io/DanIgnatov/pen/GeKMzo) from a browser and my MS Excel 2013 opened it without error messages. It seems there are differences between ExcelJS codes for browsers and for Node. I cannot check Node scenario in a short time but hope my codepen projects will help manage both issues.

**Comment by Gildewarz777** [comment]
Yes I'm using Node and this might be the issue. From a browser it works perfectly but as you said there must be some confusion in the order of the calls. I'm trying to figure out how all of this works, could you keep me updated on your check of the Node scenario? Thanks for the help

**Comment by Gildewarz777** [comment]
Hi, I'm still having difficulties with opening the file, I feel like I have tried a lot of different options. If anyone has a working example on Node I can try to debug from there and maybe fix.

**Comment by henninghaakonsen** [comment]
+1!

**Comment by Gildewarz777** [comment]
Hi, 
Upon closer inspection the excel generated in the codepen of @IgnatovDan is not working either. When I try to open it I get this error: 

![Screenshot 2019-04-05 at 10 51 19](https://user-images.githubusercontent.com/10724721/55615876-d3b0d780-5790-11e9-96ab-9737aae4de32.png)

**Comment by nicosayer** [comment]
We have the same problem. Is there any news on this issue ?

**Comment by IgnatovDan** [comment]
Could you please publish your incorrect XLSX file so I can check how Excel2013 and Office365Excel will open it and investigate what is incorrect?
This information can help us make changes in ExcelJS sources.

**Comment by AlexanderPruss** [comment]
I'm having a similar problem, except the file can be somewhat repaired by the excel dialog. I still want to get rid of whatever is causing this popup though...

**Comment by fghjfghj** [comment]
i use writeBuffer() function.Need "file-saver" lib

> workbook.xlsx.writeBuffer().then(function(buffer) {
  // done
  saveAs(new Blob([buffer], {
      type: "application/octet-stream"
   }), `example.xlsx`);
   console.log('excel export success');
});

**Comment by szilch** [comment]
Hey Community,
is there any progress on this open issue? I also tried to use the library with Node.
I made some tests but without success.
Here my setup:
- MacOs
- Node 12.16.1
- exceljs 3.9.0
- Microsoft Excel for Mac Version 16.35

I created an empty worksheet and saved it in different ways, but no file can be opened with Excel.
Even it cannot be repaired!
```
let Excel = require('exceljs');
let fs = require('fs');
//-------------------------------------------------------------------------------------
const workbookStream  = new Excel.Workbook();
const writeStream = fs.createWriteStream('./test-stream.xlsx');
workbookStream.xlsx.write(writeStream)
    .then(() => writeStream.end())
    .then(() => writeStream.close());
//-------------------------------------------------------------------------------------
const workbookFile  = new Excel.Workbook();
workbookFile.xlsx.writeFile('./test-file.xlsx')
//-------------------------------------------------------------------------------------
const workbookBuffer  = new Excel.Workbook();
workbookBuffer.xlsx.writeBuffer()
    .then(buffer => {fs.promises.writeFile('./test-buffer.xlsx', Buffer.from(buffer));
});
```
The attached file is an example of the output, which was generated.
[test-file.xlsx](https://github.com/exceljs/exceljs/files/4554933/test-file.xlsx)

**Comment by Jeremyllanta** [comment]
Hi @szilch, I'm facing the same issue. Did you find any solution on your own ?

**Comment by Serj-M** [comment]
I solved the problem. Hope this helps you.
If you download this excel file from the server side (In my case Node JS). 
The problem is solved by one line on the client side:  **req.responseType = "arraybuffer";**

```
requestData(req, "exportToExcel")
            .then(resXHR => {
                // For the correct processing of data from the server, you must specify the format/structure of data transfer
                resXHR.responseType = "arraybuffer"
                // Wait until the data is downloaded from the server
                resXHR.onload = function () {
                    // Call a modal window for saving with type and file name 
                    saveAs(new Blob([resXHR.response], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), 'users.xlsx')
                }
            })
```

**Comment by itsTalwar** [comment]
Facing the same issue when I'm trying to edit an existing excel sheet, to fix this I've done all the updates on the existing workbook and before sending the response/uploading I'm creating another workbook and looping all the sheets, rows and cell and adding the respective data and styles from the old workbook.

```
    let newWorkbook = new Excel.Workbook();
    oldWorkbook.eachSheet(function(worksheet: any) {
      let newSheet = newWorkbook.addWorksheet(worksheet.name);
      worksheet.eachRow(function(row: any) {
          newSheet.addRow(row.values)
      })
   })
```
This is for sure not the optimal way of fixing but can help you in getting unblocked, please do mind to add your row styles or cell styles while iterating to elements.

If we think about having a standard function that can take care of all this? I'll try to come up with one if anybody needs it.

**Comment by cosminmihai** [comment]
Hey guys, what can we do to speed this up?

**Comment by JulesHermans** [comment]
Faced the same issue. Find out it was because I copied a model of a different worksheet (blueprint) and by doing this the name of the worksheet (sheet) didn't match anymore with the name I created, resetting the name to the original one fixed it for me!
`var sheet = wb.addWorksheet(originalName);
 sheet.model = Object.assign(blueprintSheet.model,
      {mergeCells: blueprintSheet.model.merges});
  sheet.name = orginialName;
`

I hope this helps anyone!

**Comment by gilles-hemmerle** [comment]
I encounter the same issue. Impossible to open the generated file (even a very basic one with an empty workbook) with Excel without a corrupted file warning. It opens properly in other software like libre office, google spdreadshit, wps, etc.
I only tested to generate file from node (not from the browser).

**Comment by wildflowericecoffee** [comment]
I'm also having this error on node without "Enabling editing" manually in Excel

**Comment by mpinto1991** [comment]
did you fix this issue? i am having this too, using ...writeFile().

**Comment by Serj-M** [comment]
Hello. My file is formed on the backend using writeBuffer() and then transferred to the frontend. I use the buffer because in this format the server transmits data to the UI. 
Here's the code for handling this buffer on the frontend side - https://github.com/exceljs/exceljs/issues/739#issuecomment-629535077

**Comment by flodan** [comment]
Hi all,

is there any news to this problem? I am having the same problem:

- Create the file in the backend on a request of the frontend using `workbook.xlsx.writeBuffer()`
- The response includes the following headers:
  ```
  {
    'Content-Type': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet; charset=utf-8',
    'Content-Disposition': `attachment; filename=test.xlsx`,
  }
  ```
- When trying to open the file using MS Excel on Windows, I get a warning that the file is corrupted.

**Comment by IgnatovDan** [comment]
I tried this code (thanks to @szilch and his 'test-file.xlsx' file):

```
      var workbook = new ExcelJS.Workbook();
      
      workbook.xlsx.writeBuffer().then(function(buffer) {
          saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
      });
```
in my online demo at https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSOverview/jQuery/Light/ and MSExcel2013 shows the "We found a problem with some content in 'Employees.xlsx'" when opening the generated XLSX file.

However, the following code:
```
      var workbook = new ExcelJS.Workbook();
      var worksheet = workbook.addWorksheet('Employees');
      
      workbook.xlsx.writeBuffer().then(function(buffer) {
          saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
      });
```
generates a correct file and MSExcel opens it without errors.
It seems that MSExcel cannot open a file without a workbook.

**Comment by flodan** [comment]
> I tried this code (thanks to @szilch and his 'test-file.xlsx' file):
> 
> ```
>       var workbook = new ExcelJS.Workbook();
>       
>       workbook.xlsx.writeBuffer().then(function(buffer) {
>           saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
>       });
> ```
> 
> in my online demo at https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ExcelJSOverview/jQuery/Light/ and MSExcel2013 shows the "We found a problem with some content in 'Employees.xlsx'" when opening the generated XLSX file.
> 
> However, the following code:
> 
> ```
>       var workbook = new ExcelJS.Workbook();
>       var worksheet = workbook.addWorksheet('Employees');
>       
>       workbook.xlsx.writeBuffer().then(function(buffer) {
>           saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
>       });
> ```
> 
> generates a correct file and MSExcel opens it without errors.
> It seems that MSExcel cannot open a file without a worksheet.

Unfortunately, this does not solve my issue as I am already creating a worksheet in my code:

```
const workbook = new Workbook()
const sheet = workbook.addWorksheet(worksheetTitle)

// add rows + styling ...

return workbook.xlsx.writeBuffer()
```

**Comment by IgnatovDan** [comment]
Would you pls share your minimized xlsx file and source code? I can check it in my environment.

**Comment by flodan** [comment]
I could fix my problem. For all who stumble upon this issue, maybe the following will help:

- I had cells with text of a percentage in it (e.g. "50%"). Excel tried to parse them automatically which led to an error. I switched to insert them as a number (e.g. 0.5) and configured it to being displayed as a percentage (`0%`)
- I also had a table which I gave a name that had a space in it (e.g. "test table"). It seems that Excel does not allow that (when repairing the file, Excel replaces the space with an underscore)
- I also used the `autoFilter` feature on the table, which led to an error. I switched to enabling the filter buttons directly for each column of the table

**Comment by arungogosoon** [comment]
I face the similar problem. I tried to update excel file asynchronously from multiple places in my code simultaneously. If we try to open the file in read mode when it was in write mode already, it'll make the file corrupted. 

I was stuck in the below error. 
`
Error Error: Corrupted zip or bug: expected 16 records in central dir, got 0
    at ZipEntries.readCentralDir (/node_modules/jszip/lib/zipEntries.js:146:23)
    at ZipEntries.load (/node_modules/jszip/lib/zipEntries.js:257:14)
    at /node_modules/jszip/lib/load.js:48:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async XLSX.load (/node_modules/exceljs/lib/xlsx/xlsx.js:279:17)
    at async XLSX.readFile (/node_modules/exceljs/lib/xlsx/xlsx.js:55:24)
`

I carefully gone through my code and found that I've been asynchronously calling update excel method multiple times simultaneously. I made it to be synchronous and removed unwanted code calling update excel method. This fixes my problem.

**Comment by Lixaned** [comment]
I also facing the same issue.  I try to open the file using office 365 and found out that my Excel is empty.
I solve the problem by adding await in the write function

await workbook.xlsx.writeFile('filename.xlsx')
