### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by nextdooroldwang** [exceljs/exceljs#757]
![image](https://user-images.githubusercontent.com/18671240/53930970-41081480-40ce-11e9-8f97-1a026a0b3060.png)
![image](https://user-images.githubusercontent.com/18671240/53930981-4d8c6d00-40ce-11e9-8023-caa17fc4cc13.png)

**Comment by realeve** [comment]
the same issue

**Comment by realeve** [comment]
import Excel from 'exceljs/dist/es5/exceljs.browser.js';

**Comment by heyarne** [comment]
I am facing the same issue on node v13.1.0, but only with some `*.xlsx` files. The stacktrace looks like this:
```
TypeError: Cannot read property 'match' of undefined
    at Object.decodeEx (/home/heyarne/example/node_modules/exceljs/lib/utils/col-cache.js:158:26)
    at /home/heyarne/example/node_modules/exceljs/lib/xlsx/xform/book/workbook-xform.js:181:34
    at Array.forEach (<anonymous>)
    at Object.each (/home/heyarne/example/node_modules/exceljs/lib/utils/under-dash.js:5:13)
    at WorkbookXform.reconcile (/home/heyarne/example/node_modules/exceljs/lib/xlsx/xform/book/workbook-xform.js:174:7)
    at XLSX.reconcile (/home/heyarne/example/node_modules/exceljs/lib/xlsx/xlsx.js:82:19)
    at ZipReader.<anonymous> (/home/heyarne/example/node_modules/exceljs/lib/xlsx/xlsx.js:343:14)
```

**Comment by fnaquira** [comment]
Did you manage to solve it?

**Comment by hansonGong** [comment]
Did you manage to solve it?

**Comment by MedinaGitHub** [comment]
same problem, but before my file was a xlsb and then i convert this in xlsx
