### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by Sean-214** [exceljs/exceljs#759]
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by geoynomous** [comment]
I also get warnings from NPM. It's basically from the usage of an old version of fast-csv (3.7.0) and from cjs (which uses lodash.groupby)

Please fix asap

```
(node:9294) [DEP0111] DeprecationWarning: process.binding() is deprecated. Please use public APIs instead.
    at /Users/development/boqs/node_modules/lodash.groupby/index.js:118:39
    at Object.<anonymous> (/Users/development/boqs/node_modules/lodash.groupby/index.js:120:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/development/boqs/node_modules/fast-csv/build/src/parser/transforms/HeaderTransformer.js:9:42)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/development/boqs/node_modules/fast-csv/build/src/parser/transforms/index.js:5:27)
2020-04-23T13:33:26.033Z [ERROR]  <9294> (node:9294) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:162:11)
    at new Buffer (buffer.js:245:3)
    at Object.<anonymous> (/Users/development/boqs/node_modules/buffer-indexof-polyfill/index.js:68:9)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/development/boqs/node_modules/exceljs/node_modules/unzipper/unzip.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)

```

**Comment by alubbe** [comment]
Should be fixed with https://github.com/exceljs/exceljs/pull/1233
