### ISSUE TITLE
SOME ERROR TypeError: Cannot read property 'push' of undefined     at parseClose (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xform/sheet/data-validations-xform.js:176:35)    

### ISSUE THREAD

**Issue by sauravonga** [exceljs/exceljs#771]
Why I am getting this error.
```
SOME ERROR TypeError: Cannot read property 'push' of undefined
    at parseClose (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xform/sheet/data-validations-xform.js:176:35)
    at parseClose (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xform/sheet/worksheet-xform.js:220:24)
    at SAXStream.<anonymous> (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xform/base-xform.js:83:21)
    at emitOne (events.js:96:13)
    at SAXStream.emit (events.js:188:7)
    at Object.me._parser.(anonymous function) [as onclosetag] (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:258:17)
    at emit (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:889:7)
    at Object.write (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:1436:13)
    at SAXStream.write (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/node_modules/sax/lib/sax.js:239:18)
    at /Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:196:14
    at Promish (/Users/apple/Desktop/survapp/backend/node_modules/promish/lib/promish-class.js:24:9)
    at write (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:195:14)
    at Array.map (native)
    at _pipe (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:201:31)
    at _flush (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:265:14)
    at writeComplete (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:280:15)
    at end (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:290:7)
    at pipe (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/utils/stream-buf.js:340:12)
    at parseStream (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xform/base-xform.js:102:12)
    at Object.processWorksheetEntry (/Users/apple/Desktop/survapp/backend/node_modules/exceljs/dist/es5/xlsx/xlsx.js:136:20)
```

**Comment by vpsudhin** [comment]
Hi Team,

I'm also facing the same issue when I try to read excel file which is created in ms excel.
