### ISSUE TITLE
crashed with nestjs when updated to 2.x

### ISSUE THREAD

**Issue by Diluka** [exceljs/exceljs#953]
```log
[Nest] 26257   - 09/09/2019, 10:26:29 AM   [ExceptionHandler] Map#toJSON isn't generic +32ms
TypeError: Map#toJSON isn't generic
    at String.toJSON (/Users/Diluka/parsec/yybb-ums-api/node_modules/core-js/modules/_collection-to-json.js:6:38)
    at Function.<anonymous> (/Users/Diluka/parsec/yybb-ums-api/node_modules/core-js/modules/_ctx.js:18:15)
    at JSON.stringify (<anonymous>)
    at Function.stringify [as default] (/Users/Diluka/parsec/yybb-ums-api/node_modules/fast-safe-stringify/index.js:11:18)
    at ModuleTokenFactory.getDynamicMetadataToken (/Users/Diluka/parsec/yybb-ums-api/node_modules/@nestjs/core/injector/module-token-factory.js:22:44)
    at ModuleTokenFactory.create (/Users/Diluka/parsec/yybb-ums-api/node_modules/@nestjs/core/injector/module-token-factory.js:12:27)
    at ModuleCompiler.compile (/Users/Diluka/parsec/yybb-ums-api/node_modules/@nestjs/core/injector/compiler.js:21:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at Object.<anonymous> (/Users/Diluka/parsec/yybb-ums-api/node_modules/ts-node/src/bin.ts:158:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)

```

https://github.com/nestjs/nest/issues/1898

**Comment by MaikeMota** [comment]
I'm facing the same issue here, When construct the workbook  in a NestJS service, I 'm rollbacking my version right now while this issue stay open.

**Comment by TheNoim** [comment]
This is stupid. Why does a module itself needs to use own polyfills. @guyonroche Please remove all polyfills. If you need polyfills, you should include them by yourself.

**Comment by alubbe** [comment]
@guyonroche I think it would be better to not ship exceljs with our version of babel's polyfill and instead add to the README that it is a requirement, if needed - in other words, the consumer gets to decide if to use it and if so, what version

**Comment by jestepan** [comment]
So, 2.0.1 still crashing with NestJS? Any workarounds for this issue?

**Comment by bleuscyther** [comment]
Since i use it in angular i import the file like this:

````typescript
import * as ExcelJS from "exceljs/dist/exceljs.min.js";
````

What i did at first, i manually editing  **exceljs\dist\exceljs.js** to see if i could fix this.
from
```javascript
require('babel-polyfill');
```
to
```javascript
   if (!global || !global._babelPolyfill) {
      require('babel-polyfill')
    }
```

based on this comment: https://github.com/babel/babel-loader/issues/401#issuecomment-400257814

It works.

But  what i ended up doing was removing the multiple imports on different pages. Before the tree shaking the file was being called multiple times.



I dont think this is a definitive solution but this could help solve it: https://github.com/babel/babel-loader/issues/401
Looks like a third party package is requiring it as a dev-dependency : **prettier-eslint** in this package

**Comment by Diluka** [comment]
`3.1.0` seems ok
