### ISSUE TITLE
Unexpected xml node in parseOpen 

### ISSUE THREAD

**Issue by Tri-Vi** [exceljs/exceljs#958]
I got this issue when I tried to parse an excel file, but I'm not sure what caused the issue. Could someone help me with this?

> Error: Unexpected xml node in parseOpen: {"name":"x:sst","attributes":{"xmlns:x":"http://schemas.openxmlformats.org/spreadsheetml/2006/main"},"isSelfClosing":false}
>     at SharedStringsXform.parseOpen (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/xlsx/xform/strings/shared-strings-xform.js:124:17)
>     at SAXStream.<anonymous> (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/xlsx/xform/base-xform.js:104:19)
>     at emitOne (events.js:116:13)
>     at SAXStream.emit (events.js:211:7)
>     at SAXParser.me._parser.(anonymous function) [as onopentag] (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:258:17)
>     at emit (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:624:35)
>     at emitNode (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:629:5)
>     at openTag (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:825:5)
>     at SAXParser.write (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:1391:13)
>     at SAXStream.write (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/sax/lib/sax.js:239:18)
>     at /Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:259:14
>     at new Promise (<anonymous>)
>     at write (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:258:14)
>     at Array.map (<anonymous>)
>     at StreamBuf._pipe (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:265:31)
>     at StreamBuf._flush (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:336:14)
>     at writeComplete (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:352:15)
>     at StreamBuf.end (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:365:7)
>     at StreamBuf.pipe (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/stream-buf.js:418:12)
>     at SharedStringsXform.parseStream (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/xlsx/xform/base-xform.js:138:14)
>     at ZipReader.<anonymous> (/Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/xlsx/xlsx.js:356:43)
>     at emitOne (events.js:116:13)
>     at ZipReader.emit (events.js:211:7)
>     at /Users/tvi/Documents/BCM projects/cvd-genomics/node_modules/exceljs/dist/es5/utils/zip-stream.js:95:22
>     at <anonymous>

**Comment by straiki** [comment]
I've had same problem lately, found out why.

If you have data table in excel sheet, you need to clear all filtres unless you'll end up with this error.

![image](https://user-images.githubusercontent.com/724967/118241741-c81a5980-b49c-11eb-8e35-48f4811953d6.png)

**Comment by Emiya0306** [comment]
+1, I got these error messages.
```
/Users/xxxxx/node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:79
        throw new Error(`Unexpected xml node in parseOpen: ${JSON.stringify(node)}`);
              ^

Error: Unexpected xml node in parseOpen: {"name":"lastModifiedBy","attributes":{},"isSelfClosing":false}
    at CoreXform.parseOpen (/xxxxx/node_modules/exceljs/lib/xlsx/xform/core/core-xform.js:79:15)
    at CoreXform.parse (/xxxxx/node_modules/exceljs/lib/xlsx/xform/base-xform.js:63:16)
    at async XLSX.load (/xxxxx/node_modules/exceljs/lib/xlsx/xlsx.js:353:36)
    at async XLSX.readFile (/xxxxx/node_modules/exceljs/lib/xlsx/xlsx.js:55:24)
    at async /xxxxx/edit.js:6:3
```

**Comment by Walnussbaer** [comment]
Just stumbled across this error. So this basically means the this lib is not usable.  You cannot expect from the users of an Excel sheet that they don't use any autofilters on any worksheet. Real bummer :(
