### ISSUE TITLE
TypeError: Excel.Workbook is not a constructor

### ISSUE THREAD

**Issue by tvrashid** [exceljs/exceljs#960]

**Comment by Tenison** [comment]
How do you solve this problem

**Comment by sagungargs15** [comment]
@alexfauquette  @Tenison @tvrashid @guyonroche
Any luck on this issue ? While importing an excel file .xlsx in ReactJs + Typescript I receive a similar error 


import { Workbook } from 'exceljs';
import { Importer } from 'xlsx-import/lib/Importer';
import Dropzone, { FileWithPath, useDropzone } from "react-dropzone";

```
async function handleFileUpload() {
    return Promise.resolve(fetch('invoice.xlsx').then((r) => r.blob()));
}

    const onDrop = useCallback(async(acceptedFiles: File[]) => {
      setFiles(acceptedFiles);
      const reader = new FileReader();
      const invoiceFile = await handleFileUpload()
      reader.readAsArrayBuffer(invoiceFile);
      reader.addEventListener('loadend', async e => {
            if (reader.result instanceof ArrayBuffer) {
                        const wb =  new Workbook();
                        await wb.xlsx.load(reader.result);
                        const importer = new Importer(wb);
                        setInvoice(onImportInvoice(importer));
            }
    })


```

I am getting this Error

```
index.tsx:86 Uncaught (in promise) TypeError: exceljs__WEBPACK_IMPORTED_MODULE_1__.Workbook is not a constructor
    at FileReader.<anonymous> (index.tsx:86:1)
```

**Comment by alexfauquette** [comment]
@sagungargs15 If you're using vite or remix, the [PR linked to this issue](https://github.com/mui/mui-x/issues/5035) could be helpfull.

**Comment by Tenison** [comment]
I used excelJS. In my use case, I clone a file template.xlsx and inserted some data. I then saved it to another file at the end. Hope this helps.

```js
const runMainTemplate = () => {
    const workbook = new ExcelJS.Workbook();
    //file name to clone
    let filename = 'template.xlsx';

    workbook.xlsx.readFile(filename)
    .then(function() {
        //Accessing Sheet to clone
        let sheetA = workbook.getWorksheet("Sheet1");
        let sheetB = workbook.getWorksheet("Sheet2");
        

        insertMonthlyDataIntoTemplate(sheetA);
        //Creating new sheet
        // let row = sheetB.getRow(5);
        // row.getCell(1).value = 5; // A5's value set to 5
        // row.commit();

        return workbook.xlsx.writeFile("finalsavepoint.xlsx");
    }); 
} 

const insertMonthlyDataIntoTemplate = (worksheet) => {
    worksheet.getCell('P7').value = todaysDate();
    worksheet.getCell('Q4').value = "PERCENTAGE  SERVICE AVAILABILITY FOR THE MONTH: " + metaDataHolder.monthlyPercentage + "%";
    worksheet.getCell('I4').value = "TRANSMISSION STATION: " + metaDataHolder.station;

}
```

**Comment by sagungargs15** [comment]
@Tenison I am also using exceljs to import a file in .xlsx format in ReactJs + Typescript. I am also attaching the file for reference here. The challenge is my code is failing at the `const workbook = new ExcelJS.Workbook(); `stage because of the following error 

```
[invoice.xlsx](https://github.com/exceljs/exceljs/files/10122718/invoice.xlsx)

index.tsx:86 Uncaught (in promise) TypeError: exceljs__WEBPACK_IMPORTED_MODULE_1__.Workbook is not a constructor
    at FileReader.<anonymous> (index.tsx:86:1)
```

**Comment by vibhash1083** [comment]
Any solution for this issue? I am facing same issue with reactjs + typescript.

**Comment by tonioriol** [comment]
This was the solution for me, seems to happen in quite a bit of other imports too in a nuxt/nitro project:

```js
import * as ExcelJS from 'exceljs'

const workbook = new ExcelJS.default.Workbook()
```
As mentioned in this other issue https://github.com/mui/mui-x/issues/5035#issuecomment-1156240336, "the excelJs is imported, but set into a default property. So the constructor is not excelJS.Workbook but excelJS.default.Workbook"

**Comment by vibhash1083** [comment]
> ```js
> import * as ExcelJS from 'exceljs'
> 
> const workbook = new ExcelJS.default.Workbook()
> ```

I am getting following error while using this:

Property 'default' does not exist on type 'typeof import("node_modules/exceljs/index")'.ts(2339)

**Comment by tonioriol** [comment]
@vibhash1083 sorry to hear that. I would suggest what is mentioned in the issue comment I linked in my previous response. Do the import as I show and try to console log and see the actual shape of the ExcelJS variable.

But reading again your error output, it says “does not exist in **type**” so are you doing the import exactly the way is shown in my previous comment? Cause it seems you are doing `import type....`.

**Comment by vibhash1083** [comment]
> @vibhash1083 sorry to hear that. I would suggest what is mentioned in the issue comment I linked in my previous response. Do the import as I show and try to console log and see the actual shape of the ExcelJS variable.
> 
> But reading again your error output, it says “does not exist in **type**” so are you doing the import exactly the way is shown in my previous comment? Cause it seems you are doing `import type...`.

I am getting empyt object in a reactjs + typescript library.

**Comment by kztera** [comment]
> Any solution for this issue? I am facing same issue with reactjs + typescript.

I disabled Cache in Networking tab and problem solved

![image](https://github.com/exceljs/exceljs/assets/116504460/08064246-cb65-43b9-a162-fcff75a78cae)

**Comment by WilberthGamboa** [comment]
In my case, I had importation issues because I wanted to use ES6 imports instead of CommonJS. I managed to solve it with the following import statement.
``` javascript
import exceljs from 'exceljs';
const { Workbook } = exceljs;
const workbook = new Workbook();

```
**Remember that if you want to use ES6, you need to change the "type" to "module" in the package.json.**

**Comment by musthafa1996** [comment]
> In my case, I had importation issues because I wanted to use ES6 imports instead of CommonJS. I managed to solve it with the following import statement.
> 
> ```js
> import exceljs from 'exceljs';
> const { Workbook } = exceljs;
> const workbook = new Workbook();
> ```
> 
> **Remember that if you want to use ES6, you need to change the "type" to "module" in the package.json.**

Thank you. This worked for me in my ESM set up.

**Comment by AdamGaskins** [comment]
Instead of 

```js
import * as ExcelJS from 'exceljs'
```

try

```js
import ExcelJS from 'exceljs'
```
